### ISSUE TITLE
Make an interactive web gui for merge conflict resolution

### ISSUE THREAD

**Issue by martinal** [jupyter/nbdime#11]

**Comment by ellisonbg** [comment]
The new JupyterWorkbench/Lab will be a perfect place to build this UI.

On Mon, Dec 14, 2015 at 6:21 AM, Martin Sandve Alnæs <
notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/martinal/nbdime/issues/11>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by martinal** [comment]
Sounds great. Where can I read more about this? What's the timeline for this project?

**Comment by ellisonbg** [comment]
@cameronoelsen

**Comment by martinal** [comment]
Closing this as we're beyond "make", other more specific issues should be created to cover any problems or improvements.
