### ISSUE TITLE
Lots of build dependencies

### ISSUE THREAD

**Issue by ml31415** [jupyter/nbdime#113]
npm, tornado, ... All I want is some nicer git diffs. Does it really need to have all these dependencies for that, no way to have that optional?

**Comment by vidartf** [comment]
It should be possible to make the web tools as an optional feature (extras_require), or separate it out. Not sure what is the best way to achieve this.

**Comment by vidartf** [comment]
I think the `--skip-npm` option for the install is as far as we're going to take this, together with the fact that releases (sdist/bdist) will not require `npm`. The tornado dependency will not be made optional, as it is so commonly required by other notebook tools as well.
