### ISSUE TITLE
nbmerge-web shows nothing

### ISSUE THREAD

**Issue by martinal** [jupyter/nbdime#116]
To reproduce:
```
cd nbdime/tests/files
nbmerge-web -o tmp-merged.ipynb single_cell_nb.ipynb single_cell_nb--changed_source_output_ec.ipynb single_cell_nb--changed_source_output.ipynb
```
Only the file dialogues and save/close buttons are displayed, but the buttons don't work.

**Comment by vidartf** [comment]
Ran same command here, and the browser console output is `Error: Currently not able to handle decisions on variable "execution_count"`. This is the same as the remaining issue in #64.

**Comment by vidartf** [comment]
That said, better error handling is high on the todo-list, and we should take a discussion on how to best implement this.

**Comment by vidartf** [comment]
With #118 merged for better user error feedback, the rest of this issue is tracked by #64.
