### ISSUE TITLE
"Outputs changed" shown on cell deletion

### ISSUE THREAD

**Issue by martinal** [jupyter/nbdime#129]
When a cell is deleted, the diff shouldn't show "output changed" as if that was a separate event.

![screenshot from 2016-11-17 13-03-09](https://cloud.githubusercontent.com/assets/378115/20388687/50ea1284-acc6-11e6-8a54-7599ad8cdd37.png)

(Also note that in an ideal world, the last cell in the pictured notebook would've been classified as modified and not deleted/added).

**Comment by vidartf** [comment]
Looks like the output renders are also aligned on the wrong side (left/right). I'm on it.
