### ISSUE TITLE
Allow customizing approximate-equality predicates based on json path

### ISSUE THREAD

**Issue by martinal** [jupyter/nbdime#14]
The main use case for this is to compare notebook cells based on source only, although it can easily be useful in other cases as well.

One design choice would be, instead of passing around a callable `compare(a, b)`, passing a callable `compare(a, b, path)` where path is a list of the keys into the json object to reach a and b.

One question is whether this path should include list indices, i.e. for the case:
```
nb1 = { "cells": [ { "source": "foo", ... },  { "source": "bar", ... } ] }
nb2 = { "cells": [ { "source": "bat", ... } ] }
```
when comparing "bar" and "bat", should the compare get arguments:
```
approximately_equal = compare("bar", "bat", ["cells", "source"])
```
or:
```
approximately_equal = compare("bar", ["cells", 1, "source"], "bat", ["cells", 0, "source"])
```
Note that including indices in the path requires passing separate paths, and I don't know what to use that index for so I'm leaning towards dropping it.

Example naive compare function for illustration:
```
def mycompare(a, b, path):
    if path == ["cells"]:
        return compare_sources(a["source"], b["source"])
    else:
        return a == b
```

**Comment by vidartf** [comment]
As far as I can tell, this is currently working in master, so this could be closed?
