### ISSUE TITLE
Update docs for next release

### ISSUE THREAD

**Issue by willingc** [jupyter/nbdime#141]
@martinal @minrk Opening this as a checklist for any doc updates prior to the next release. Please add or update. Happy to pitch in before after Thanksgiving holiday here.

- [x] Review installation instructions in Sphinx docs
- [x] Review installation instructions in README
- [x] Add any new features/functionality to Sphinx docs
- [x] Add a changelog doc (Initial release yay!)

**Comment by martinal** [comment]
Thanks! We're aiming for initial release next week, in addition to another iteration on the documentation there are some minor issues we'd like to fix first to make the merge tools more usable.

**Comment by vidartf** [comment]
What remain here? Only changelog, or is there any other new features/functionality?

**Comment by vidartf** [comment]
I guess we should remove difftool docs, as per #147?

**Comment by vidartf** [comment]
Mergetool docs should probably include the shortcut `nbdime mergetool` = `git mergetool --tool=nbdimeweb *.ipynb`.

**Comment by minrk** [comment]
I'd leave the difftool docs for now, while we don't have an implementation of #147. I've got a PR coming shortly finishing up the various TODO items, then we should be set.

**Comment by minrk** [comment]
I don't think we should have too many ways to call these things. I would leave out the `nbdime mergetool` doc, and possibly remove the `nbdime` entrypoint. I think it's handy to have `python -m nbdime` for certain cases, but I don't think `nbdime nbdiff` is helpful, for instance.

**Comment by martinal** [comment]
Agree on not having too many ways to call. Which cases are `python -m nbdime` useful for? If the only use is to allow running with specific python version, which can be useful for testing, then maybe we can just keep it but not document it?

**Comment by minrk** [comment]
> If the only use is to allow running with specific python version, which can be useful for testing, then maybe we can just keep it but not document it?

That's the main one. I'm happy to have it, but not cover it in the sphinx docs.

**Comment by vidartf** [comment]
I wanted to include the `nbdime mergetool` shortcut, as it is much easier to remember than `git mergetool --tool=nbdimeweb *.ipynb` (which is also a bit of a hassle to write).

**Comment by minrk** [comment]
Ah, that makes sense. The rest don't as much, though. Plus, shouldn't the alias just be for `git mergetool --tool=nbdimeweb`, not including the paths?

**Comment by vidartf** [comment]
Without the file extension filter, our mergetool will then also be called for other files, which it cannot handle. If notebooks are conflicted at the same time as other files, you should first call `nbdime mergetool`, then you should be OK to call normal tool like `git mergetool` for any conflicts on other files.

**Comment by minrk** [comment]
But if you include the inputs in the alias, you can't call it for a specific file, e.g. `mergetool foo.ipynb`.

**Comment by vidartf** [comment]
That is correct. So either the command should be updated to take an optional path argument that defaults to *.ipynb, or we can say that if you want to specify a path, you have to use the git command.

**Comment by martinal** [comment]
Like this?

https://github.com/jupyter/nbdime/pull/191

**Comment by vidartf** [comment]
👍
