### ISSUE TITLE
images with relative URLs don't appear in web diffs

### ISSUE THREAD

**Issue by minrk** [jupyter/nbdime#146]
often images are loaded with relative URLs (either in markdown or output). These should be visible in rendered diffs.

cf https://github.com/jupyterlab/jupyterlab/pull/560

**Comment by vidartf** [comment]
This can be implemented by allowing access to the needed files on the server. This will have some ramifications that need to be addressed:
 - Security wise, we will change from only giving access to *.ipynb files, to all files.
 - For URLs that refer to a parent directory, the web server will have to be started in the outer folder. not sure how big of an issue this is.

A possible alternative solution is to replace such images with a placeholder image. This issue should only happen when trying to render the markdown, which is currently only done for unchanged cells. The placeholder could therefor be something like "<image unchanged>". However, if we want to switch to using a rendered markdown diff in the future, we would no longer be able to side step the issue like this.

**Comment by vidartf** [comment]
Thinking about this again, I think we can just replace external images with a placeholder which says "external image (\<path\>)". We're only interested in if the path has changed (changes to the actual images should be picked up by the VCS).

**Comment by martinal** [comment]
Makes sense to me.
