### ISSUE TITLE
workaround git difftool config 

### ISSUE THREAD

**Issue by minrk** [jupyter/nbdime#147]
There's a problem in git where files with custom diff drivers cannot be passed to diff tools. This means that setting up `git difftool --tool nbdime`  can never work while the nbdime git *driver* is registered.

If nbdiff-web could take git refs as args, we could workaround this by talking to git directly, rather than dealing with git's internal configuration conflicts.

**Comment by minrk** [comment]
after working on the release for a bit and facing this a few times, I think we should drop difftool support, and just go for `nbdiff-web` accepting git refs. Feature for 0.2.

**Comment by vidartf** [comment]
👍
