### ISSUE TITLE
Add merge strategy options

### ISSUE THREAD

**Issue by martinal** [jupyter/nbdime#19]
For example git merge has options like 'use ours'/'use theirs' to force conflict resolution, and we can add notebook-specific merge options like 'clean all notebook output', 'clean conflicting notebook output', 'join conflicting notebook output', and many more. We should sketch some use cases to figure out which options will be useful and try to keep the set small.

**Comment by martinal** [comment]
The notebook merge algorithm can be something along the lines of

* compute notebook specific diffs base->local, base->remote
* apply generic merge algorithm based on these diffs, producing a partially merged document and conflicts in the form of the parts of the diffs that have not been applied
* resolve conflicts in notebook-specific ways based on user arguments discussed below
* return remaining conflicts for manual resolution

Some generic conflict resolution strategies are:

* manual: resolve in some external mergetool (i.e. the planned CLI for simple cases, webgui for richer features)
* use-base: in case of conflict, keep original value (can make sense for some metadata, e.g. the kernelspec)
* use-local and use-remote: use changes from one version when they conflict (can make sense for some metadata or output cells, and with source code for certain use cases, e.g. if remote contains functionality and local contains cosmetic changes that can safely be thrown away)
* invalidate: remove field or make empty (natural choice for execution counts)
* join: concatenate items, intended for output cells to avoid immediate data loss but avoid conflict resolution work, possibly with some markers inserted
* inline: for source conflicts, we can store the conflicts inline in the source cells, using <<< >>> markers known from regular diff/merge tools, and this way we can do manual conflict resolution by editing a regular notebook, complete with regular execution features while merging.

For different types of notebook data, different strategies are natural. Warnings can be emitted for the auto-resolved conflicts, and any thrown away data can be stored in a document on the side if wanted. I believe these defaults will produce a sensible and useful initial behaviour before we get a full merge UI up and running:

* invalidate for execution counts and possibly other transient fields
* use-base for hidden metadata such as the kernel spec
* join or invalidate for output cells
* inline for source

Feel free to suggest additional strategies, and better names for the above.

**Comment by martinal** [comment]
The basics are in place, what's missing is mostly more testing and documentation, and making the options user-configurable instead of hardcoded (see nbdime/merging/notebooks.py)

**Comment by koaning** [comment]
Stackoverflow link that might be useful to mention here. http://stackoverflow.com/questions/36914806/jupyer-ipython-notebook-and-git-merge
