### ISSUE TITLE
All merge strategies on non-leaf nodes need bundled decisions

### ISSUE THREAD

**Issue by martinal** [jupyter/nbdime#197]
Including 'union', and 'record-conflict'.

Typical symptom:
```
    def patch_dict(obj, diff):
        newobj = {}
        deleted_keys = set()
    
        for e in diff:
            op = e.op
            key = e.key
            assert isinstance(key, string_types)
>           assert key not in newobj
E           AssertionError

nbdime/patching.py:95: AssertionError
```

We should consider rewriting the merge code to apply strategies earlier instead of creating decisions first and then collecting them again.

**Comment by vidartf** [comment]
To me, the biggest open question is when transients checks should be applied. If that can be (correctly) included in bundling code, I think we can make our job easier.

**Comment by martinal** [comment]
If we apply strategies early as I suggest there would be no need for bundling decisions afterwards.

Take a look at the inline conflicts handler for attachments in this PR:
https://github.com/jupyter/nbdime/pull/194
notice how it has to re-do basically the entire merge of the attachments dict?

In the original dict the diff on e.g. `/cells/3/attachments` should already be bundled in a patch.

I don't remember why we didn't do it that way initially, have I forgotten something important?
