### ISSUE TITLE
Could nbdime conceivably be run as a service within Jupyterhub?

### ISSUE THREAD

**Issue by Analect** [jupyter/nbdime#199]
Looking at the documentation for the new 'services' capability within Jupyterhub, there's an example of what an instance of nbviewer might look like as a service [here](https://github.com/jupyter/nbviewer#securing-the-notebook-viewer).  I was wondering if nbdime could be   bolted on to Jupyterhub the same way, and are the required attachment mechanisms in place for this?

In the context of Jupyterlab 'components' that would be used to display a side-by-side diff, would something like the 'notebook' component be used ... or would it require a whole other class of component such as a HTML File Viewer (akin to the existing Markdown File Viewer) in order to be able to view output like that depicted below, taken from a recent nbdime demo/talk.

![image](https://cloud.githubusercontent.com/assets/4063815/21009920/1a072bc2-bd41-11e6-8bd6-7020be172d30.png)

**Comment by minrk** [comment]
It could be a JupyterHub service, but a JupyterLab extension is perhaps the most logical place for this to happen. We definitely have a plan to do this, but are waiting a little bit for the JupyterLab extension mechanism to settle down (and we have to put our time into other things for a bit).

If you would like to explore the prospect of an nbdime JupyterLab extension, that would be great! I don't think we are planning to put any time into that before the end of February (grant deliverable due dates). My understanding of the main difficulty in integrating with JupyterLab is that we would like to take *two* files as input, and a lot of JupyterLab is built around taking actions on single files.

**Comment by Analect** [comment]
Great. Thanks for the clarification, as ever.  I'll close this out for now.
