### ISSUE TITLE
Format diff in human readable text format

### ISSUE THREAD

**Issue by zonca** [jupyter/nbdime#2]
interesting project! I tested the plugin on two sample notebooks you have as tests:

```
jupyter nbdiff test-data-singlecell-1.ipynb test-data-singlecell-2.ipynb a.json
! cells
    -- 0-1
    ++ 0-1
        [{u'cell_type': u'code',
          u'execution_count': None,
          u'metadata': {u'collapsed': True},
          u'outputs': [],
          u'source': u'def mult(a, b):\n    "This version is debugged."\n    return a * b'}]
```

is there an option to pretty-print the diff in a more human readable format?

**Comment by martinal** [comment]
Not yet but that's a goal. Thanks for testing.

**Comment by martinal** [comment]
nbdiff now presents the diff in a more friendly format for many cases, still not perfect but better.

**Comment by martinal** [comment]
Consider matching this better:

https://en.wikipedia.org/wiki/Diff_utility#Unified_format
