### ISSUE TITLE
develop install fails

### ISSUE THREAD

**Issue by michaelaye** [jupyter/nbdime#201]
I'm trying a dev install on macOS 10.11.6.
Tried both brew npm (which install nodejs and npm) and the pkg install from the linked Node.js website in the docs. Both times I get this, after doing `pip install -e .`:

```bash
   npm ERR! Darwin 15.6.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
    npm ERR! node v6.9.2
    npm ERR! npm  v3.10.9
    npm ERR! code ELIFECYCLE
    npm ERR! nbdime-webapp@0.1.0 build: `webpack`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the nbdime-webapp@0.1.0 build script 'webpack'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the nbdime-webapp package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     webpack
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs nbdime-webapp
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls nbdime-webapp
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/klay6683/Dropbox/src/nbdime/nbdime/webapp/npm-debug.log
    rebuilding js and css failed
    missing files: ['/Users/klay6683/Dropbox/src/nbdime/nbdime/webapp/static/build/nbdime.js']
```
The requsested npm-debug.log is here:
https://gist.github.com/f24c03a5976ac9cd7aaf376be04f576b

I have zero experience with `npm` so I hope this is all you need as info?

**Comment by vidartf** [comment]
Was able to reproduce locally. Can you confirm if #203 fixes it for you?

**Comment by michaelaye** [comment]
i retried with master ( b691ab5a6648a0f4aaefd5e741dffb289e015f6f) but still get the error. 
What about the missing file mentioned, `nbdime.js` ? Is that something that is missing in the repo, or created by the installation process and it's missing because something fails upfront?

**Comment by vidartf** [comment]
This seems strange. Could you try to run the JS/TS compile commands manually:

```
<backup any changes you have>
git clean -xdf
cd nbdime-web
npm install
npm run build   <--- This should be the step that fails currently
cd ../nbdime/webapp
npm install
npm run build
```

**Comment by michaelaye** [comment]
This went through fine. At the step of `npm run build` this happened:

```bash
(stable) └─❱❱❱ npm run build                                                           +7192 16:09 ❰─┘

> nbdime@0.1.0 build /Users/klay6683/Dropbox/src/nbdime/nbdime-web
> tsc --project src && node scripts/copy-files.js
```
So, as above I get missing files messages, somehow this copying fails with the `pip install` ?

**Comment by vidartf** [comment]
It's an npm/typescript issue (`tsc` is the typescript compiler). There are some obscure references to similar errors out there, but I am not able to reproduce or figure out how to solve it. Do you have `tsc` available globally before the install?

**Comment by minrk** [comment]
A global install being:

    npm install -g typescript

**Comment by michaelaye** [comment]
not sure i understand the question, but i can say that i never did anything with tsc before trying this install.

**Comment by vidartf** [comment]
What is the output of `npm list -g | grep "typescript\|tsc"`?

**Comment by vidartf** [comment]
Closing as inactive, as I cannot reproduce, and more information is needed to figure out if this is an issue with nbdime or 3rd party tools.

**Comment by roycegit** [comment]
I experience the same tsc error above and I realized my issue.  The directory ".bin" under $ROOT/node_modules was not present due to the fact that I did a "cp -r" on a "quickstart" directory to clone it and the copy did not copy over the ".bin" directory.

I manually copied the ".bin" directory under node_modules and tsc now worked.

**Comment by ralphcallaway** [comment]
not a jupyter guy, but used to run into this alot on mac when I copied an existing project to the new directory, tsc would still be in `/node_modules/.bin/tsc` but it would fail it's require. running `npm install` wouldn't fix it. 

was able to resolve it consistently by deleting `/node_modules` and re-running `npm install`, looks like the install process may build something special that doesn't survive a directly copy and requires a clean `npm install`

**Comment by vishalims095** [comment]
just remove node_module folder
and install all dependency again (npm i)
