### ISSUE TITLE
Ability to specify port for `git difftool --tool nbdime file.ipynb`

### ISSUE THREAD

**Issue by shuvrobiswas** [jupyter/nbdime#207]
Hi All,

Whenever, I run the following command in my git project, the git diff viewer opens at a random port

`git difftool --tool nbdime file.ipynb`

Is there a way to specify the port (this is important say for working on a aws server where not all ports may be open).

Brilliant tool btw!

**Comment by vidartf** [comment]
If you look at your git config (edit file, or by `git config` CLI), you should find an entry:
```
[difftool "nbdime"]
	cmd = git-nbdifftool diff \"$LOCAL\" \"$REMOTE\"
```

To add a port, change the cmd to be `git-nbdifftool diff --port 9876 \"$LOCAL\" \"$REMOTE\"`.

Note: This will prevent you from launching more than one instance of the difftool at once, as the port will be taken when trying to launch a second instance.

**Comment by vidartf** [comment]
PS: The `--port`/`-p` option should be available for all entry points that launch a web server.

**Comment by shuvrobiswas** [comment]
Thanks mate! 1st solution worked, however running `git difftool --tool nbdime --port 5555 file.ipynb` or `git difftool --port 5555 --tool nbdime file.ipynb` in the command line leads to `fatal: ambiguous argument '5555': unknown revision or path not in the working tree.` In any case all good as 1st solution is working :)

**Comment by vidartf** [comment]
Yeah, `git` unfortunately doesn't pass along any extra arguments, so we cannot get to them. That is why they have to go in the git config (but all *direct* calls to nbdime entry points should take port argument 😄).

**Comment by shuvrobiswas** [comment]
@vidartf ahh ok, that makes sense! Thanks again for pointing out the right solution :)
