### ISSUE TITLE
Conflicting default location for git attributes file

### ISSUE THREAD

**Issue by baldwint** [jupyter/nbdime#219]
When enabling the diff and merge drivers in git with no configured value for `core.attributesFile`, nbdime will write attributes information to a new file at `~/.gitattributes`, even though this is not the default location for the attributes file. The [git documentation](https://git-scm.com/docs/gitattributes) states

> Attributes that should affect all repositories for a single user should be placed in a file specified by the core.attributesFile configuration option (see git-config[1]). Its default value is $XDG_CONFIG_HOME/git/attributes. If $XDG_CONFIG_HOME is either not set or empty, $HOME/.config/git/attributes is used instead.

As a result, a novice user following the [git integration quickstart](http://nbdime.readthedocs.io/en/latest/index.html#git-integration-quickstart) will find that it doesn't work (assuming that they, like me, do not have `core.attributesFile` explicitly set).

**Comment by baldwint** [comment]
Here is a patch that changes this behavior to write to the default location. I wasn't sure how to approach writing an automated test for the `global_` branch of this function, but I manually checked that it fixes the quickstart on my machine (MacOS 10.11.6 El Cap). I have not tested that it works on an OS which uses `$XDG_CONFIG_HOME`.

**Comment by minrk** [comment]
Fixed by #220
