### ISSUE TITLE
Not great installation instructions

### ISSUE THREAD

**Issue by amueller** [jupyter/nbdime#221]
Without thinking I copy & pasted the installation instructions:

> pip install --upgrade nbdime

That's pretty bad, as it tries to pip upgrade all dependencies - which are conda packages on my system.
So now I broke my jupyter-core and nbformat.

So if you want to include ``--upgrade``, please also include ``--no-dep``. Thanks :)

**Comment by minrk** [comment]
`--upgrade` and `--no-dep` is a pretty rough combination, since it explicitly allows for broken dependencies. I'd go for removing `--upgrade`.
