### ISSUE TITLE
Enabling the git diff/merge tool fails if user hasn't configured git

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/nbdime#229]
I ran `git-nbdiffdriver config --enable --global` on a new system before I had configured git and got:

```
Traceback (most recent call last):
  File "/opt/conda/bin/git-nbdiffdriver", line 11, in <module>
    load_entry_point('nbdime==0.2.0.dev0', 'console_scripts', 'git-nbdiffdriver')()
  File "/opt/conda/lib/python3.5/site-packages/nbdime/gitdiffdriver.py", line 106, in main
    opts.config_func(opts.global_)
  File "/opt/conda/lib/python3.5/site-packages/nbdime/gitdiffdriver.py", line 47, in enable
    with io.open(gitattributes, 'a', encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ellisonbg/.config/git/attributes'
```

**Comment by ellisonbg** [comment]
Hmm, but even after I configured git (name, email) I only had a `.gitconfig` file and installation failed. I had to mkdir the git dir and touch the attributes file for installation to work.

**Comment by baldwint** [comment]
Good find. I can definitely replicate the part about having to create `~/.config/git` if it doesn't exist already, but I didn't find that I had to touch the `attributes` file.

This is related to a recent change made for #219. I changed the default location for gitattributes but neglected to check whether the parent directories exist.
