### ISSUE TITLE
Global Git configuration written to wrong gitattributes file

### ISSUE THREAD

**Issue by timtroendle** [jupyter/nbdime#231]
I've enabled ndime 0.1.0 for my Git installation on a Mac [in accordance to the docs](https://nbdime.readthedocs.io/en/latest/vcs.html#command-line-registration) with:

     git-nbdiffdriver config --enable --global

Leading to the correct entries being written to the wrong `.gitattributes` file, and so nbdime was not used for diffing with Git. The changes were made to `~/.gitattributes` while I was using the Git default [which is ~/.config/git/attributes](https://git-scm.com/docs/gitattributes). As I wasn't using a global gitattributes file before, the following command obviously solved the problem for me:

    git config --global core.attributesfile ~/.gitattributes

but I think this should be either mentioned in the docs, or nbdime should be able to infer the actual location of `core.attributesfile`.

**Comment by minrk** [comment]
This is fixed by #220. Will release 0.1.1 later today.
