### ISSUE TITLE
Try to get nbdime used by github

### ISSUE THREAD

**Issue by vidartf** [jupyter/nbdime#243]

**Comment by willingc** [comment]
Hi @bkeepers,

I enjoyed meeting you at the wont_fix unconference at GH a couple of weeks ago. It was a lovely event, and I like GH's direction with opensource.guide (I shared with hundreds of students at Hack Illinois this past weekend).

I wanted to follow up on a conversation with Lee and others about possibly seeing if GitHub could incorporate nbdime for diffing Jupyter/IPython notebooks that GitHub renders. Would you mind pointing us in the right direction of who/where we should formally share this request with at GH?

Thanks :smile:

Carol

cc/ @minrk @vidartf

**Comment by sixers** [comment]
Is it possible to create a JavaScript extension for Github? One of the ways to do this is to fetch diff data via API, and just provide a GUI on top of Github.

**Comment by bkeepers** [comment]
Hey @willingc, it was great to meet you too!

support@github.com is the best place to send feature requests. Our support team does a great job of cataloging feature requests so our engineering teams can see them.

**Comment by willingc** [comment]
Thanks @bkeepers for the direction. We'll send it over formally (though I think it has been raised in some informal talks already).

**Comment by Analect** [comment]
For what it's worth, I added a [comment](https://gitlab.com/gitlab-org/gitlab-ce/issues/2508#note_25365522) to this thread over on Gitlab, since there are efforts underway there to try to get a basic notebook viewer implemented.  It could be that @vidartf or @sixers above could enhance the conversation over there and discuss the possibilities of gitlab being able to leverage the nbdime accomplishments.

**Comment by Analect** [comment]
FYI. Basic implementation for viewing notebooks has been added to master on Gitlab [here](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/10017).  Still may be worth engaging with them to get nbdime working on that platform.

**Comment by joelostblom** [comment]
There is now a [GitLab issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/46539) for adding rich diff support to notebooks.

**Comment by amit1rrr** [comment]
I built [ReviewNb](https://reviewnb.com), a diff'ing tool for notebooks stored on GitHub. It can generate diffs for GitHub commits/pull requests (screenshot below). 

You can read more about it [here](https://towardsdatascience.com/introducing-reviewnb-visual-diff-for-jupyter-notebooks-6797e6dfa20c). It can be used until nbdime is integrated into Github diff.

![screenshot 2018-10-23 at 12 44 04 pm](https://user-images.githubusercontent.com/1350490/47634104-4a103480-db76-11e8-9763-ed0f8bc93a49.png)

**Comment by gwincr11** [comment]
https://github.blog/changelog/2023-03-01-feature-preview-rich-jupyter-notebook-diffs/

**Comment by minrk** [comment]
Huzzah!

**Comment by gwincr11** [comment]
Congrats and thanks for building a cool tool. Hope to meet you at Jupyter Conf.
