### ISSUE TITLE
building the webapp to expose the preliminary api as a service

### ISSUE THREAD

**Issue by Analect** [jupyter/nbdime#244]
@vidartf 
I may be jumping the gun here, but is there a basic dockerfile available that will install and then run the nbdime [webapp](https://github.com/jupyter/nbdime/blob/master/nbdime/webapp/nbdimeserver.py).

I manually installed a dev version, following [this](https://nbdime.readthedocs.io/en/latest/installing.html#installing-latest-development-version) and then tried running `python nbdime/webapp/nbdimeserver.py -p 8888`, but wasn't able to get anything running.  Maybe this is still a WIP.

I was experimenting around getting a number of 'services' running under jupyterhub, using kubernetes and wanted to add nbdime as a service in order to potentially be able to access its [API](https://nbdime.readthedocs.io/en/latest/restapi.html).  Is this viable to do, as yet?

Thanks.

**Comment by vidartf** [comment]
I haven't made any dockerfiles, no.

To run the base server, I think you might have to run it as a module (`python -m nbdime.webapp.nbdimeserver <args>`). That is at least how I always run it (it also allows you to run it from whatever folder you want). You should also be able to do this with the stable release.

The given REST API documentation is not really updated. We need to go over that.

**Comment by Analect** [comment]
Thanks @vidartf 

when you run up `(env) root@test1:/home/me/jupyter/nbdime# python -m nbdime.webapp.nbdimeserver`, do you expect to see some output?

Navigating to `server-ip:8888" (the default port, I think) doesn't render anything?  Would you be able to add a screenshot of what I should expect to see?

```
(env) root@test1:/home/me/jupyter/nbdime# python -m nbdime.webapp.nbdimeserver -h
usage: nbdimeserver.py [-h] [--version]
                       [--log-level {DEBUG,INFO,WARN,ERROR,CRITICAL}]
                       [-p PORT] [-b BROWSER] [-w WORKDIRECTORY]

Web interface for Nbdime.

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  --log-level {DEBUG,INFO,WARN,ERROR,CRITICAL}
                        Set the log level by name.
  -p PORT, --port PORT  specify the port you want the server to run on.
                        Default is 8888.
  -b BROWSER, --browser BROWSER
                        specify the browser to use, to override the system
                        default.
  -w WORKDIRECTORY, --workdirectory WORKDIRECTORY
                        specify the working directory you want the server to
                        run from. Default is the actual cwd at program start.
```

**Comment by vidartf** [comment]
Normally when it just starts, it is quiet. If you add `-p/--port` argument I think you get some log output. You can add `--log-level DEBUG` to get some more information about what is wrong (maybe).

**Comment by vidartf** [comment]
Also, currently nbdime only listens to 127.0.0.1. We would need some updating to safely listen to non-local interfaces.

**Comment by Analect** [comment]
@vidartf 
Following up on your comment:
>  nbdime only listens to 127.0.0.1. We would need some updating to safely listen to non-local interfaces.

I've been working on getting a number of 'services' set up under jupyterhub, including 'nbviewer' and 'nbdime'. For this I created a Dockerfile (below) for the development version of nbdime, which probably needs some tweaking, as it's currently running as root, however installing using my user 'nbdime' was failing on permissioning issues ...

```
FROM python:3.6
WORKDIR /home/
RUN mkdir -p /home/jupyter
WORKDIR /home/jupyter
RUN git clone https://github.com/jupyter/nbdime

# Configure Environment
ENV NBDIME_DIR /home/jupyter/nbdime
ENV NB_USER nbdime
ENV NB_UID 1000

# Create nbdime user with UID=1000 and in the 'users' group
RUN useradd -m -s /bin/bash -N -u $NB_UID $NB_USER && \
    mkdir -p $NBDIME_DIR && \
    chown $NB_USER $NBDIME_DIR

WORKDIR /home/jupyter/nbdime
RUN python -m venv env
RUN /bin/bash -c "source env/bin/activate; pip install nodeenv; nodeenv -p; pip install -e ."

#USER $NB_USER
EXPOSE 9000

CMD ["./env/bin/python3", "-m", "nbdime.webapp.nbdimeserver", "--port=9000", "--log-level=DEBUG"]
```

Anyway, from the hub logs, it seems both services are running and recognised.
```
[I 2017-01-25 23:00:31.428 JupyterHub app:973] Adding API token for service: nbviewer
[I 2017-01-25 23:00:31.444 JupyterHub app:973] Adding API token for service: nbdime
[I 2017-01-25 23:00:31.648 JupyterHub app:1453] Hub API listening on http://0.0.0.0:8081/hub/
[I 2017-01-25 23:00:32.288 JupyterHub app:1143] Proxy already running at: http://10.7.241.229:80/
[W 2017-01-25 23:00:32.294 JupyterHub orm:282] Adding missing route for nbviewer (<Server(10.7.255.140:8080)>)
[I 2017-01-25 23:00:32.294 JupyterHub orm:163] Adding service nbviewer to proxy /services/nbviewer => http://10.7.255.140:8080
[W 2017-01-25 23:00:32.296 JupyterHub orm:282] Adding missing route for nbdime (<Server(10.7.240.164:9000)>)
[I 2017-01-25 23:00:32.296 JupyterHub orm:163] Adding service nbdime to proxy /services/nbdime => http://10.7.240.164:9000
[I 2017-01-25 23:00:32.299 JupyterHub app:1485] JupyterHub is now running at http://10.7.241.229:80/
[I 2017-01-25 23:00:32.301 JupyterHub orm:163] Adding service nbviewer to proxy /services/nbviewer => http://10.7.255.140:8080
[I 2017-01-25 23:00:32.301 JupyterHub orm:163] Adding service nbdime to proxy /services/nbdime => http://10.7.240.164:9000
```
And, while I can navigate to the running nbviewer at '/services/nbviewer/' (see 1 below), the same can't be said for '/services/nbdime/' (as per 2 below). From the logs above, the container running nbdime at 'http://10.7.240.164:9000' is getting proxied correctly back to '/services/nbdime/'.

Here are the logs from nbdime and below them are the JUPYTERHUB env variables that are used to pass relevant info to the nbdime service .. or at least that's how it works in nbviewer.

```
kubectl logs nbdime-deployment-2630675095-jhv0t
[D nbdimeserver:263] Using params: {'port': 9000, 'cwd': '/home/jupyter/nbdime'}
....
JUPYTERHUB_SERVICE_NAME=nbdime
JUPYTERHUB_BASE_URL=http://jupyterhub.dummy.com
JUPYTERHUB_API_TOKEN=<redacted>
JUPYTERHUB_API_URL=http://hub:8081/hub/api
JUPYTERHUB_SERVICE_PREFIX=/services/nbdime/
```

![image](https://cloud.githubusercontent.com/assets/4063815/22313313/3e9db7ce-e354-11e6-9841-0952d833fd49.png)

Rather then the error in 2 above .. I suppose I should be expecting to see something like what's below at the '/services/nbdime/' end-point. Is that correct?

![image](https://cloud.githubusercontent.com/assets/4063815/22313641/8084e756-e355-11e6-8b00-5650b6a42771.png)

Would you know of anything that might be blocking nbdime from working as a proxied service in this set-up?   Thanks for your insights.

**Comment by minrk** [comment]
I think nbdime can only listen on localhost, which is the problem here. nbdime needs to be told to listen on a different IP for this.

@vidartf can you add an `--ip` arg to the webapps?

**Comment by vidartf** [comment]
See #255 for proposed fix.

**Comment by Analect** [comment]
@vidartf @minrk 
Thanks for your efforts to try to get this working as a service.
Could I just check with you how you think this might work, in the context of a kubernetes cluster ... something that I have working for nbviewer below.

In the context of the cluster, nbdime will be running in its own pod ... and then the webapp is exposed via a <pod-ip>:9000 (I'm over-riding the default port 8888).  As per nbviewer below, the ip of the pod is getting set based on ENV variables passed from a service exposing nbdime in kubernetes, so that these can be used to pass through to the `url` parameter below, as set in jupyterhub_config.py.

Does the --ip argument you are implementing require that an ip be pre-specified specified when running the `nbdime.webapp.nbdimeserver` command? (see below).  More importantly, is this ip going to be the same as the pod-ip ... ie. (how jupyterhub is going to find nbdime)? It's just that in the case of kubernetes, this isn't going to be known up-front ... and an internal kubernetes IPs can get changed depending on whether a pod has to restart.  

`CMD ["./env/bin/python3", "-m", "nbdime.webapp.nbdimeserver", "--port=9000", "--log-level=DEBUG"]`

```
c.JupyterHub.services = [
    {
        'name': 'nbviewer',
        'url': 'http://' + os.environ['NBVIEWER_SERVICE_HOST'] + ':' + os.environ['NBVIEWER_SERVICE_PORT'],
        'admin': True,
        'api_token': os.environ['NBVIEWER_JHUB_TOKEN']
    },
    {
        'name': 'nbdime',
        'url': 'http://' + os.environ['NBDIME_SERVICE_HOST'] + ':' + os.environ['NBDIME_SERVICE_PORT'],
        'admin': True,
        'api_token': os.environ['NBDIME_JHUB_TOKEN']
    }
]
```
I'm happy to try to test this if/when that pull request gets merged.

**Comment by vidartf** [comment]
Not sure if I understood all the details of what you are trying to do, but I'll try to clear up the role of the new `--ip` argument:
 - If set, set server will listen on the device of that IP. E.g. if the IP is `127.0.0.1`, it will only listen on localhost. If the IP is `0.0.0.0` it will listen on all interfaces. If the device is X.Y.Z.W, it will only listen on the device which that IP maps to.
 - The `--ip` argument will also be used when trying to open a browser for tools, but that will not be applicable when starting `nbdimeserver` directly.

For your case, I think you command should probably be:
```
CMD ["./env/bin/python3", "-m", "nbdime.webapp.nbdimeserver", "--port=9000", "--log-level=DEBUG", "--ip=0.0.0.0"]
```

**Comment by Analect** [comment]
@vidartf 
Sorry it's taken me a few days to come back to you on this. I tested your implementation of the `--ip` argument by generating a docker [image](https://gist.github.com/Analect/f454a3239f6ae3d963215f7809bf748f) based on your `web-ip-arg` branch behind [this](https://github.com/jupyter/nbdime/pull/255) pull request.  As per your suggestion above, I'm setting `--ip=0.0.0.0`.  However, perhaps I'm still missing part of the puzzle, since I'm still not able to get anything like the screenshot below at the end-point `/jupyterhub.myserver.com/services/nbdime/`.  Instead I get a `404 Error`.

![image](https://cloud.githubusercontent.com/assets/4063815/22681416/ff34ad12-ed04-11e6-8a67-1335e9f5c92e.png)

I've set things up very similarly to `nbviewer`, in terms of how parameters are passed from `env variables` within the kubernetes cluster back to jupyterhub_config.py (below).

```
c.JupyterHub.services = [
    {
        'name': 'nbviewer',
        'url': 'http://' + os.environ['NBVIEWER_SERVICE_HOST'] + ':' + os.environ['NBVIEWER_SERVICE_PORT'],
        'admin': True,
        'api_token': os.environ['NBVIEWER_JHUB_TOKEN']
    },
    {
        'name': 'nbdime',
        'url': 'http://' + os.environ['NBDIME_SERVICE_HOST'] + ':' + os.environ['NBDIME_SERVICE_PORT'],
        'admin': True,
        'api_token': os.environ['NBDIME_JHUB_TOKEN']
    }
]
```
The `NBDIME_SERVICE_HOST` and `NBDIME_SERVICE_PORT` parameters above get derived from with the nbdime pod from env variables below.

```
root@hub-deployment-1003321966-qm69m:/srv# env | grep NBDIME_SERVICE
NBDIME_SERVICE_HOST=10.7.255.220
NBDIME_SERVICE_PORT=9000
```
Based on logs from the 'hub' below, it seems that is connecting with the `nbdime` service appropriately, however, I'm not seeing an equivalent hand-shake for nbdime as I am for nbviewer like this: `/hub/api/authorizations/cookie/jupyterhub-services/[secret] (nbviewer@10.4.6.14)`

```
[I 2017-02-07 07:34:08.914 JupyterHub log:100] 302 GET /hub/oauth_callback?code=35e5e59229c520b8a95b20bb738d0a018dcab50ca4f89e1e8d6fc013bc9cb085 (@10.4.6.16) 299.60ms
[I 2017-02-07 07:34:08.958 JupyterHub log:100] 200 GET /hub/home (mccoole@10.4.6.16) 10.54ms
[I 2017-02-07 07:34:12.600 JupyterHub log:100] 200 GET /hub/admin (mccoole@10.4.6.16) 29.23ms
[I 2017-02-07 07:34:23.181 JupyterHub log:100] 200 GET /hub/api/authorizations/cookie/jupyterhub-services/[secret] (nbviewer@10.4.6.14) 11.53ms
[W 2017-02-07 07:35:55.301 JupyterHub orm:282] Adding missing route for nbviewer (<Server(10.7.247.160:8080)>)
[I 2017-02-07 07:35:55.301 JupyterHub orm:163] Adding service nbviewer to proxy /services/nbviewer => http://10.7.247.160:8080
[W 2017-02-07 07:35:55.304 JupyterHub orm:282] Adding missing route for nbdime (<Server(10.7.249.17:9000)>)
[I 2017-02-07 07:35:55.305 JupyterHub orm:163] Adding service nbdime to proxy /services/nbdime => http://10.7.249.17:9000
```
From nbviewer [docs](http://jupyterhub.readthedocs.io/en/latest/services.html#externally-managed-services), it seems certain `JUPYTERHUB_*` parameters get supplied into the pod running nbviewer for use by that service.  I'm doing the equivalent for nbdime (see below), although I don't necessarily think that these are consumed by the nbdime service the same way that nbviewer does and this could be why I'm not getting nbdime working in conjunction with the hub. Could this be the case?  Perhaps @minrk has some insights here.

```
JUPYTERHUB_SERVICE_NAME=nbdime
JUPYTERHUB_BASE_URL=http://jupyterhub.myserver.com
JUPYTERHUB_API_TOKEN=af77de208e83ea673ac90653226bb03cf4962bdb8dccb4a3605e12eec239530c
JUPYTERHUB_API_URL=http://hub:8081/hub/api
JUPYTERHUB_SERVICE_PREFIX=/services/nbdime/
```
For completeness, these are the logs from the nbdime pod, when I try to hit the `/jupyterhub.myserver.com/services/nbdime/` end-point.

```
2017-02-06T22:20:00.077184387Z [D nbdimeserver:263] Using params: {'port': 9000, 'ip': '0.0.0.0', 'cwd': '/home/jupyter/nbdime'}
2017-02-06T22:25:45.681606999Z [W web:1971] 404 GET /services/nbdime/ (10.4.6.6) 1.12ms
2017-02-06T22:25:54.296755163Z [W web:1971] 404 GET /services/nbdime/ (10.4.6.6) 0.82ms
```
... and these are the equivalent from the nbviewer pod on hitting the `/jupyterhub.myserver.com/services/nbviewer/` endpoint.
```
2017-02-06T22:16:42.901548548Z [I 170206 22:16:42 app:124] Not indexing notebooks
2017-02-06T22:16:42.901895546Z [I 170206 22:16:42 app:144] Using in-memory cache
2017-02-06T22:16:42.986968923Z [I 170206 22:16:42 app:308] Listening on 0.0.0.0:8080, path /services/nbviewer/
2017-02-06T22:25:23.609167200Z [I 170206 22:25:23 log:53] 200 GET /services/nbviewer/ (10.4.6.6) 1490.27ms
```

Ultimately, I'm hoping to be able to pass a few notebooks for 'diffing' to something like a [localdiff](http://nbdime.readthedocs.io/en/latest/restapi.html#localdiff) end-point ... so I would be passing a payload like:

```
{
  "base":   "filename.ipynb",
  "remote": "filename.ipynb",
  "args": json_diff_args
}
```
... to an endpoint like ``/jupyterhub.myserver.com/services/nbdime/localdiff`.
Is that the intended way one should interact with the nbdime API?
Thanks.

**Comment by Analect** [comment]
Any chance of some guidance here before this gets lost as a closed issue.

**Comment by vidartf** [comment]
Just popping it open until its resolved :)

**Comment by minrk** [comment]
I'll try to build an example with this one to see if I can figure out what's missing. `base_url` seems like a likely case.

**Comment by Analect** [comment]
@minrk 
Is there anything I can test for you in terms of checking whether `base_url` might be the source of the problem., as per your comment above.  I note that for nbviewer, there is an explicit setting of hub-related settings [here](https://github.com/jupyter/nbviewer/blob/a5b59fe71a5e35736080a1f331ce6fb4a110f4fc/nbviewer/app.py#L235-L237), but there's nothing equivalent in nbdime.  

```
hub_api_token=os.getenv('JUPYTERHUB_API_TOKEN'),
hub_api_url=os.getenv('JUPYTERHUB_API_URL'),
hub_base_url=os.getenv('JUPYTERHUB_BASE_URL'),
```

It's not clear to me whether the parameters passed from the hub via `c.JupyterHub.services` up [here](https://github.com/jupyter/nbdime/issues/244#issuecomment-277925608) is enough for nbdime to work as a service within hub.

**Comment by minrk** [comment]
it's nbdime where a `base_url` arg is needed to support running the app on a prefix. This needs to be done on both the javascript and the Python side.

In general, no absolute URLs should occur anywhere in the application - everything should start with `{base_url}`.

**Comment by minrk** [comment]
#260 gets support started, but I don't have time to finish it right now. I hope to get to it soon, but someone else can finish it if they get there before me.

**Comment by Analect** [comment]
Thanks @minrk

**Comment by lc0** [comment]
@vidartf @Analect I am doing something similar and unfortunately it works on local machine, but not in my k8s
I am getting:
```
Blocking request with non-local 'Host' 55.55.55.55 (55.55.55.55:80). If the notebook should be accessible at that name, set NotebookApp.allow_remote_access to disable the check.
```

Event that nbdime was started with `--ip` option, like:
```
[D nbdimeserver:357] Using params: {'port': 80, 'ip': '0.0.0.0', 'cwd': '/usr/src', 'base_url': '/'}
```

**Comment by lc0** [comment]
btw, the issue was resolved in https://github.com/jupyter/nbdime/releases/tag/1.0.5
