### ISSUE TITLE
static files for web app don't get installed via pip

### ISSUE THREAD

**Issue by eteq** [jupyter/nbdime#247]
The proximate problem is that if I just install from `pip` using `pip install nbdime` (which gets me v0.1.1), and then do ``nbdime-web <nb1> <nb2>``, the app pops up, but nothing works (i.e., the form comes up but hitting "diff files" does nothing).  The console shows:
```
[I nbdimeserver:274] Listening on 127.0.0.1, port 50680
[I nbdiffweb:48] URL: http://127.0.0.1:50680/diff?base=nb1.ipynb&remote=nb2.ipynb
[E web:2678] Could not open static file '[redacted]/miniconda3/envs/scratch/lib/python3.5/site-packages/nbdime/webapp/static/nbdime.js'
[I web:1971] 200 GET /diff?base=nb1.ipynb&remote=nb2.ipynb (127.0.0.1) 4.09ms
[W web:1971] 404 GET /static/nbdime.js (127.0.0.1) 0.80ms
[W web:1971] 404 GET /static/nbdime.js (127.0.0.1) 0.76ms
```

When I look at ``.../site-packages/nbdime/webapp``, it exists, but has no ``static`` directory... That's weird because I see ``'webapp/static/**/*.*'`` is already in the `package_data` of the `setup.py`... But maybe it's because it's not in `MANIFEST.in`?

(If it matters, this is with conda 4.2.13, py 3.5.2, and OS X 10.11)

**Comment by timstaley** [comment]
I see this with Ubuntu / virtualenv usage too - so I think it's fair to say it's broken for most people who are trying out nbdime via a pip install.

**Comment by timstaley** [comment]
Ah! found the relevant typo. PR fix coming up.

**Comment by vidartf** [comment]
Thanks for both the report and the PR 👍
