### ISSUE TITLE
Document integration with mercurial

### ISSUE THREAD

**Issue by ngoldbaum** [jupyter/nbdime#250]
As far as I can tell, nothing in `nbdime` is git-specific. However, the docs heavily emphasize git. I'd like to add a section explaining how to integrate `nbdime` as an external merge tool with mercurial.

**Comment by vidartf** [comment]
This would be very welcome! The buildup of nbdime is intentionally made to not be git-specific, and mercurial has always been the next obvious target. It simply hasn't been prioritized. If you are familiar with mercurial, a PR documenting integration would be a good way to start, and if there are any special entry points needed we'd of course be happy to add those.

**Comment by vidartf** [comment]
Reading up on this, I see that the mercurial external differ needs to be able to diff directories, see https://www.mercurial-scm.org/wiki/ExtdiffExtension. This is currently not supported, and it seems this would need to be added before we could add support for mercurial.

**Comment by vidartf** [comment]
A work-in-progress PR for solving this is now available in #250.

**Comment by afriggeri** [comment]
We'd like to start using nbdime to simplify integrating Jupyter notebooks in our workflows, but we have a Mercurial repo so I'm not sure we can do this yet. My understanding of the current PR is that there are still a couple more things to do here before it can be merged, is anyone currently working on this? I'd be happy to help although I'm unfamiliar with what's needed. Thanks!

**Comment by vidartf** [comment]
It would be very helpful if you could install nbdime from the PR (#289), and add the config listed there to your mercurial config. You would then diff using `hg nbdime` or `hg nbdimeweb`. The merge driver would be used for norebook files by default then, and conflicts can be resolved by `hg resolve --tool nbdime-web` (dashes in name should probably be made consistent before merging).

Any and all feedback would help move this along quicker :)
