### ISSUE TITLE
Documentation and installation needs some clarification

### ISSUE THREAD

**Issue by jbwhit** [jupyter/nbdime#263]
I ended up powering through and being moderately successful, but I feel that a lot of places in the documentation could be made more clear. To start things off here is my setup as requested by your guidelines for contributing link: 

```python -c "import IPython; print(IPython.sys_info())"

{'commit_hash': '5c9c918',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/Users/jonathan/miniconda3/envs/svdspy3/lib/python3.5/site-packages/IPython',
 'ipython_version': '5.1.0',
 'os_name': 'posix',
 'platform': 'Darwin-16.4.0-x86_64-i386-64bit',
 'sys_executable': '/Users/jonathan/miniconda3/envs/svdspy3/bin/python',
 'sys_platform': 'darwin',
 'sys_version': '3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, '
                '17:52:12) \n'
                '[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]'}
```

Following directions from https://nbdime.readthedocs.io/en/latest/ the pip install works. Then, trying the git integration: 

```$nbdime config-git --enable
Unrecognized command 'config-git'

Usage: nbdime [OPTIONS]

OPTIONS: -h, --version, COMMANDS{show, diff, merge, diff-web, merge-web, mergetool}

Examples: nbdime --version
          nbdime show -h
          nbdime merge-web

Documentation: https://nbdime.readthedocs.io.
```

Right, so the installed `nbdime` version is 0.1.2 -- and the documentation is for 0.2.0.dev -- so scroll down to the instructions for installing the most up-to-date dev version: 

```
$ pip install -e git+https://github.com/jupyter/nbdime
Could not detect requirement name, please specify one with #egg=
```

Also fails.

Fine, I'll git clone the repo; pip install -e; now have version 0.2.0.dev. 

```$ nbdime config-git --enable
No .git directory in ., skipping git attributes
No .git directory in ., skipping git attributes
```

This command apparently has to be run in the top level of a git repository? If so, this should probably be noted somewhere. Rerunning in top level directory of a git repo appears to work.

So, the original task that I wanted to do was to look at this commit: https://github.com/jbwhit/one-offs/commit/9269f47ae688c0e7963e01b44b47a551b907538c but with `nbdiff-web`. It's a single, updated Notebook. I just want to see the change that I made to this notebook. Using git I'd do something like: 

```$ git diff HEAD^ HEAD notebooks/2017-02-16_jbw_nbdime.ipynb
nbdiff /var/folders/lb/s1z87djn41s8r15zly9t81500000gp/T//YG2aYa_2017-02-16_jbw_nbdime.ipynb notebooks/2017-02-16_jbw_nbdime.ipynb
--- /var/folders/lb/s1z87djn41s8r15zly9t81500000gp/T//YG2aYa_2017-02-16_jbw_nbdime.ipynb  2017-02-16 16:59:02
+++ notebooks/2017-02-16_jbw_nbdime.ipynb  2017-02-16 16:33:56
## modified /cells/3/source:
@@ -1,3 +1,3 @@
# Create# Remove outlier
# x[10] = 20.0
# y[10] = 200.0

## inserted before /cells/4/outputs/0:
+  output:
+    output_type: display_data
+    data:
+      image/png: iVBORw0K...<snip base64, md5=ffc736d96193c3d6...>
+      text/plain: <matplotlib.figure.Figure at 0x110d7ad68>
+    metadata (unknown keys):
+      image/png:
+        height: 537
+        width: 538

## deleted /cells/4/outputs/0:
-  output:
-    output_type: display_data
-    data:
-      image/png: iVBORw0K...<snip base64, md5=b4c923ce4baca43d...>
-      text/plain: <matplotlib.figure.Figure at 0x11145ca20>
-    metadata (unknown keys):
-      image/png:
-        height: 537
-        width: 538
```

Which works as expected. However, the following:

```
$ nbdiff-web diff HEAD^ HEAD notebooks/2017-02-16_jbw_nbdime.ipynb
usage: nbdiff-web [-h] [--version]
                  [--log-level {DEBUG,INFO,WARN,ERROR,CRITICAL}] [-p PORT]
                  [-b BROWSER] [--ip IP] [-w WORKDIRECTORY]
                  base remote
nbdiff-web: error: unrecognized arguments: HEAD notebooks/2017-02-16_jbw_nbdime.ipynb
```

Does not. The only place in the documentation that shows a demonstration of using this is `nbdiff-web notebook_1.ipynb notebook_2.ipynb`. So, what's the best practice for doing this?

I tried a bunch of things to try to get the `nbdiff-web` command to do something useful.

```
$ git difftool --tool=nbdiff-web HEAD^ HEAD notebooks/2017-02-16_jbw_nbdime.ipynb
nbdiff /var/folders/lb/s1z87djn41s8r15zly9t81500000gp/T//FhfY78_2017-02-16_jbw_nbdime.ipynb notebooks/2017-02-16_jbw_nbdime.ipynb
--- /var/folders/lb/s1z87djn41s8r15zly9t81500000gp/T//FhfY78_2017-02-16_jbw_nbdime.ipynb  2017-02-16 17:05:12
+++ notebooks/2017-02-16_jbw_nbdime.ipynb  2017-02-16 16:33:56
## modified /cells/3/source:
@@ -1,3 +1,3 @@
# Create# Remove outlier
# x[10] = 20.0
# y[10] = 200.0

## inserted before /cells/4/outputs/0:
+  output:
+    output_type: display_data
+    data:
+      image/png: iVBORw0K...<snip base64, md5=ffc736d96193c3d6...>
+      text/plain: <matplotlib.figure.Figure at 0x110d7ad68>
+    metadata (unknown keys):
+      image/png:
+        height: 537
+        width: 538

## deleted /cells/4/outputs/0:
-  output:
-    output_type: display_data
-    data:
-      image/png: iVBORw0K...<snip base64, md5=b4c923ce4baca43d...>
-      text/plain: <matplotlib.figure.Figure at 0x11145ca20>
-    metadata (unknown keys):
-      image/png:
-        height: 537
-        width: 538
```

But I couldn't figure out how to get the nbdiff-web view. 

Can I not compare the git diff directly -- if so, how? Or do I have to write a new file that is the same as file in the previous commit, and compare those two?

Thanks for your work and contribution here, I hope that seeing these docs through my eyes provides useful input!

**Comment by vidartf** [comment]
Hi, and thanks for the report! First-time user logs can be really helpful in figuring out which bits needs tuning/polish!

I'll do a "chronological" reply to the different points as I see them:
 - Issue with doc content vs what is available by `pip install`: This is simply an issue of latest/stable on readthedocs. Maybe we could set the default to point to stable? This is mostly an issue before the CLI has stabilized.
 - `nbdime config-git --enable` line: I guess the docs should explicitly add the optional ` [--global | --system]` flags to that line, and explain what the signify directly below. Currently this is explained further below, but it probably makes more sense to have this here.
 - To make the web-view work with git, it needs to be launched as a tool (`git difftool --tool=nbdime`). Unfortunately, there is an issue (bug?) with git where you cannot have both the git diff driver, and the git diff tool work at the same time... We are tracking a workaround in #147, which would make `nbdiff-web` take git references, as you initially tried.

**Comment by vidartf** [comment]
Going through the docs again, I noticed that the usage documentation for the diff and merge tools are hidden under the `Command line registration` headers. These should probably be made more visible (moved up on the git integration page).
