### ISSUE TITLE
git config install broken

### ISSUE THREAD

**Issue by beckermr** [jupyter/nbdime#264]
The docs say this

<img width="798" alt="screen shot 2017-02-17 at 10 15 43 am" src="https://cloud.githubusercontent.com/assets/5296416/23073126/165ee41a-f4fa-11e6-8b60-27b077235c45.png">

but when I try to actually use this feature I get this

<img width="652" alt="screen shot 2017-02-17 at 10 16 36 am" src="https://cloud.githubusercontent.com/assets/5296416/23073162/3524caae-f4fa-11e6-8868-420e3d89d88a.png">

**Comment by vidartf** [comment]
Hi, thanks for the report!

This is an issue w.r.t. the docs: The latest docs refer to the development version, and not the released version (that is available here: http://nbdime.readthedocs.io/en/stable/). Therefore the docs for this new feature go up before the feature is available in PyPI.

A new release will probably come out next week, which will bring these into sync again. Until then you can:
 - Install the dev version from the repo.
 - Install as per the stable docs.

**Comment by beckermr** [comment]
Thank you for the clarification!
