### ISSUE TITLE
finding that Export diff button in the context of nbdime working as external jhub service not working

### ISSUE THREAD

**Issue by Analect** [jupyter/nbdime#266]
As suggested by @vidartf over [here](https://github.com/jupyter/nbdime/pull/260#issuecomment-281032844), I'm adding this as a separate issue.

Running this command against a running nbdime ...
(jupyterhub.myserver.com is a dummy instance)

`http://jupyterhub.myserver.com/services/nbdime/?base=https%3A%2F%2Fraw.githubusercontent.com%2Fjupyter%2Fnotebook%2F4671bb9cb7252d52fcf82e3fae727f4a1ca4e6a7%2Fdocs%2Fsource%2Fexamples%2FNotebook%2FWhat%2520is%2520the%2520Jupyter%2520Notebook.ipynb&local=&remote=https%3A%2F%2Fraw.githubusercontent.com%2Fjupyter%2Fnotebook%2F1b51230e8ba5164a7b92d7dea79cf27d26ae78cb%2Fdocs%2Fsource%2Fexamples%2FNotebook%2FWhat%2520is%2520the%2520Jupyter%2520Notebook.ipynb`

...  I am able to see the small change between versions.

![image](https://cloud.githubusercontent.com/assets/4063815/23121685/4c8a65ee-f759-11e6-8c07-f2b1a85d3d2e.png)

If I then hit the Export diff button, I would expect some file with differences to get generated, however nothing happens.  As per screenshot above, nothing gets actioned in the browser console.

I see the following in the nbdime logs.
`2017-02-20T10:36:35.880490826Z [I web:1971] 200 GET /services/nbdime/static/nbdime.js.map (10.4.6.129) 212.62ms`

I have tried this against Chrome Version 56.0.2924.87 on windows ... and Chrome Version 55.0.2883.87 (64-bit) on linux.

**Comment by vidartf** [comment]
The "Export diff" button is entirely client side, so it is expected behavior to not hit the server in any way.

Before debugging this further, I would recommend that you uninstall nbdime completely and do a re-install in order to get the typescript sources recompiled. Sometimes there are issues like this when switching between branches / updating.

**Comment by Analect** [comment]
@vidartf 
I end up building from master each time as I'm generating a docker image using this [Dockerfile](https://gist.github.com/Analect/f6eaabd8962aed508db517969fe7c111) based on the dev version install docs.  Is it missing anything obvious?

**Comment by vidartf** [comment]
@Analect Do you see different behavior if you run/connect to localhost? Maybe there is some not-obvious security settings interfering.

**Comment by Analect** [comment]
@vidartf 
In the container running nbdime, I ran `curl localhost:9000/services/nbdime/static/nbdime.js.map` which is the end-point suggested from the logs when the Export diff button is pressed.

As you see below, this does generate a file if I output to `test`.  So appears to work in a local context.
```
root@nbdime-deployment-1222371601-1bsb6:/home/jupyter/nbdime# curl localhost:9000/services/nbdime/static/nbdime.js.map > test    
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2523k  100 2523k    0     0  80.6M      0 --:--:-- --:--:-- --:--:-- 82.1M
root@nbdime-deployment-1222371601-1bsb6:/home/jupyter/nbdime# ls -ltra test
-rw-r--r-- 1 root root 2584273 Feb 20 14:50 test
```

**Comment by vidartf** [comment]
@Analect The export button is pure JS functionality (relies on existing content in browser), i.e. no-interactions with the server once the button is visible. The output you got from the server above is not the exported diff (that simply loads the JS used for nbdime).

I do think I figured out what it was though. Can you confirm that it works if you use the `diff` page:
`http://jupyterhub.myserver.com/services/nbdime/diff?base=https%3A%2F%2Fraw.githubusercontent.com%2Fjupyter%2Fnotebook%2F4671bb9cb7252d52fcf82e3fae727f4a1ca4e6a7%2Fdocs%2Fsource%2Fexamples%2FNotebook%2FWhat%2520is%2520the%2520Jupyter%2520Notebook.ipynb&local=&remote=https%3A%2F%2Fraw.githubusercontent.com%2Fjupyter%2Fnotebook%2F1b51230e8ba5164a7b92d7dea79cf27d26ae78cb%2Fdocs%2Fsource%2Fexamples%2FNotebook%2FWhat%2520is%2520the%2520Jupyter%2520Notebook.ipynb
`

**Comment by Analect** [comment]
@vidartf 
Yes, that works. So previously, the default url generated when comparing files on the `/services/nbdime` end-point excluded `diff`.  Was that by design?

**Comment by vidartf** [comment]
The index page allows for both diffing and merging, depending on how many boxes are filled in. The `diff` and `merge` pages makes the number of expected input explicit.
