### ISSUE TITLE
Exclude cell's output from the diff

### ISSUE THREAD

**Issue by F-A** [jupyter/nbdime#273]
It would be very nice if there were an option to filter out the cell's output when displaying the diff in the command line.
In this way, one would to see only the changes made in the cell's code or markdown.

**Comment by vidartf** [comment]
I agree. User could even configure the git driver to use such options by default. This should be relatively easy, given that we already have this for nbshow. If you need it in the mean time, you could install a git filter that strips outputs from the notebooks (such tools exists).

**Comment by F-A** [comment]
Yes, I was using git filter before. It works well however the cells output
is not tracked in this case...


On 10 Mar 2017 18:28, "Vidar Tonaas Fauske" <notifications@github.com>
wrote:

I agree. User could even configure the git driver to use such options by
default. This should be relatively easy, given that we already have this
for nbshow. If you need it in the mean time, you could install a git filter
that strips outputs from the notebooks (such tools exists).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jupyter/nbdime/issues/273#issuecomment-285731617>, or mute
the thread

**Comment by parmentelat** [comment]
I'd like to +1 on this one

as far as I am concerned, I would even not mind having a tool that is *always* ignoring the outputs - although I can also see some rare cases where the current behaviour can come in handy as well

what I am trying to say is ignoring the outputs could become the default IMHO

-- 
OTOH I would argue that comparing the (notebook) metadata would make sense most of the time too

**Comment by vidartf** [comment]
Fix proposed in #276.

**Comment by F-A** [comment]
Thanks for implementing this! Is there an easy way to use this with the git-drivers?

**Comment by vidartf** [comment]
I thought so, but it seems I forgot to add the functionality into the diff driver (only CLI app it doesn't work with!). I submitted a PR to add this in #281. After that, you should be able to add the flags in the git config (c.f. http://nbdime.readthedocs.io/en/latest/vcs.html#manual-registration).

**Comment by F-A** [comment]
Sorry, to insist but could you maybe give a brief example on how to use it with diff-driver?
I tried (in version 0.3) setting the following in .git/config:
`    [diff "jupyternotebook"]
          command = git-nbdiffdriver diff -s
`
but the output are still displayed...

**Comment by vidartf** [comment]
It works for me, but there is a caveat: For cells that have been added/removed, the full cell is shown (with outputs and metadata). Is that what you are seeing?

**Comment by vidartf** [comment]
Simple test: does `git diff` show something different than `nbdiff -s` ?

**Comment by F-A** [comment]
Ok, I was seeing outputs of newly created cells due to the caveat your mention. It actually works! Thank you very much for your help and this feature!
