### ISSUE TITLE
install instructions not working?

### ISSUE THREAD

**Issue by amueller** [jupyter/nbdime#274]
I tried
```
pip install -e git+https://github.com/jupyter/nbdime
```
and it yields
> Could not detect requirement name, please specify one with #egg=

I'm not sure -e makes sense with a github repo. Can you explain what the intention is?

**Comment by minrk** [comment]
> I'm not sure -e makes sense with a github repo.

I think it's a pretty standard use of `-e`. `-e` with a repo clones the repo into `src` (or `$VIRTUAL_ENV/src` if using envs) and does `pip install -e` from there. It was just missing the extra `#egg=nbdime`, which I thought had become optional in recent versions of pip.

**Comment by amueller** [comment]
huh, ok, I never used it that way, excuse my ignorance ;)

**Comment by wotanii** [comment]
> It was just missing the extra #egg=nbdime, which I thought had become optional in recent versions of pip.

I still get this error with `pip 9.0.1`

**Comment by vidartf** [comment]
@wotanii Did you add the `#egg=nbdime` part?

**Comment by wotanii** [comment]
First I left out the `-e` and it worked. 

Now I tried again, with the added `egg=nbdime` part and it works, too.
