### ISSUE TITLE
Nbdime in a docker image - need help with dependecies probably

### ISSUE THREAD

**Issue by MichalDulemba** [jupyter/nbdime#285]
Hi, i'm working on putting a docker with nbdime to make it even more easy to work with your app.
But i run into issues with getting information from docker outside. 
When i expose specific port using docker, and i use specific port in your app - i still get nothing.

https://github.com/MichalDulemba/nbdime-docker/blob/master/README.md

Docker image:
https://hub.docker.com/r/dulemba/nbdime-docker/

I added all dependecies but phosphor because i don't know which one you are using.

Can you help me so more people can use it? :)

**Comment by minrk** [comment]
isolating an app that needs access to your local files like nbdime in docker seems like it would make it harder to work with, not easier. What problem are you trying to solve by running nbdime in docker?

In any case, my guess is what you are running into is the fact that nbdime listens on localhost, whereas publishing docker ports only exposes *public* ports in the container. I believe that you need to tell nbdime to listen on a public ip `--ip=0.0.0.0` in order for docker's port forwarding to work.

I still wouldn't recommend running nbdime in docker on a local system, though.

**Comment by vidartf** [comment]
Closing as stale/answered, please reopen if there are any other outstanding things!
