### ISSUE TITLE
[SOLVED] Using nbdiff-web with git not possible, or at least not clear

### ISSUE THREAD

**Issue by LindyBalboa** [jupyter/nbdime#286]
I've read https://nbdime.readthedocs.io/en/latest/vcs.html several times over and see no option for this. Is this in the works or even possible?

I've tried the following:
```
nbdiff-web HEAD~1:Untitled.ipynb  HEAD:Untitled.ipynb 
git difftool --tool=nbdiff-web HEAD~1:Untitled.ipynb  HEAD:Untitled.ipynb 
```

**Comment by vidartf** [comment]
The latest docs are for the development version. A new released is planned shortly, which will include this feature.

**Comment by LindyBalboa** [comment]
Is this active in the latest git version? Is there a PR for this I could look at?
