### ISSUE TITLE
Request: Add filtering for ExecuteTime nbextension

### ISSUE THREAD

**Issue by michaelaye** [jupyter/nbdime#288]
Currently, the notebook extension ExecuteTime creates a lot of noise in the diffs.
Can `nbdime` be taught to ignore those?

```diff
## modified /cells/0/metadata/ExecuteTime/end_time:
-  2017-04-21T01:25:36.661573Z
+  2017-04-24T16:35:44.300040Z

## modified /cells/0/metadata/ExecuteTime/start_time:
-  2017-04-21T01:25:33.965884Z
+  2017-04-24T16:35:44.270200Z

## added /cells/0/metadata/init_cell:
+  True

## replaced /cells/2/execution_count:
-  2
+  23

## modified /cells/2/metadata/ExecuteTime/end_time:
-  2017-04-21T01:25:38.459810Z
+  2017-04-24T16:35:45.939762Z
```

Using nbdime 0.3.0 via conda-forge. Python 3.6, all updates current from conda-forge

**Comment by vidartf** [comment]
Currently, there is only the option to ignore metadata (`-M`/`--ignore-metadata` flag). You might also have success by adding a general git filter that strips such metadata on staging. The first will simply hide the metadata from the diff view, while the second should prevent the changes from entering the repo at all.

A more fine-grained feature could possibly take a list of paths to ignore (e.g. `/cells/*/metadata/ExecuteTime` here).

**Comment by michaelaye** [comment]
Thanks! I think a list of paths to ignore, configurable, would be a nice feature.
In the meantime, how can I activate the `--ignore-metadata` via `git diff`? I tried:

```bash
git diff -- --ignore-metadata filepath
```
but that doesn't work, even so it doesn't give an error about an unsupported flag.

**Comment by vidartf** [comment]
You need to open your git config (`git config -e`, possibly with `--global`/`--system` flag as appropriate), and change the nbdime diff command (i.e. add the `--ignore-metadata`/`-M` flag there). The docs should have a paragraph on manual config you can consult.

**Comment by vidartf** [comment]
[Link to the relevant doc section](http://nbdime.readthedocs.io/en/latest/vcs.html#manual-registration). 

Here, the modification would be:
```
command = git-nbdiffdriver diff --ignore-metadata
```

**Comment by baldwint** [comment]
In looking into this I found that include flags (e.g. `--sources`) will work in a git config but ignore flags (`--ignore-metadata`) do not. When `gitdiffdriver.py` hands off to `nbdiffapp.py` it treats ignore flags the same as no flag at all. A bug, I think. I wrote PR #290 to fix it.

**Comment by vidartf** [comment]
I'm going to close this for now. Feel free to comment/reopen if there are still any issues/confusion.
