### ISSUE TITLE
Diff does not show indentation changes

### ISSUE THREAD

**Issue by cfbolz** [jupyter/nbdime#293]
I am using nbdime and I had the following problem with it today. I was editing this Python code:

```python
with open("numbers.txt") as f:
    l = []
    for line in f:
        l.append(float(line.strip()))
    l.sort()
    l.reverse()
```

To this code:

```python
with open("numbers.txt") as f:
    l = []
    for line in f:
        l.append(float(line.strip()))
l.sort()
l.reverse()
```

Ie I changed the indentation of the last two list. However, the diff looked like this:

```
## modified /cells/2/source:
@@ -13,5 +13,5 @@ with open("numbers.txt") as f:
    l = []
    for line in f:
        l.append(float(line.strip()))
l.sort()
l.reverse()
```

with no coloring at all, which made me think nothing had changed. I think indentation changes should be shown much more prominently, particularly for a Python tool!

**Comment by vidartf** [comment]
This seems to be an issue with our use of `git` for rendering the diff to console. Which platform are you on? Also, can you confirm that setting [these two values](https://github.com/jupyter/nbdime/blob/master/nbdime/prettyprint.py#L34-L35) (`use_git` and `use_diff`) to `False` works?

**Comment by cfbolz** [comment]
I'm on Ubuntu 16.04. I don't think it has anything two do with ``git``. If I use ``nbdiff`` directly, I get the same problem. I have two ipynb files that differ only in indentation (for the content look at the bottom of the comment). 

Calling nbdiff gives this output (I tried both orders to see whether indenting or dedenting look different):
![nbdiff](https://user-images.githubusercontent.com/85942/27047530-c0448bac-4fa8-11e7-9203-d2554615aedd.png)

In the web view this looks great! But on the console it's very confusing.

If I set both ``use_git`` and ``use_diff`` to ``False``, I get a normal line-based diff:

![image](https://user-images.githubusercontent.com/85942/27047898-f5f683bc-4fa9-11e7-8e8a-65547051dc64.png)


The files look like this:

```
cfbolz@goerdeler:/tmp$ cat x1.ipynb 
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "if 1:\n",
    "    print(1)\n",
    "    print(2)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```

```
cfbolz@goerdeler:/tmp$ cat x2.ipynb 
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "if 1:\n",
    "    print(1)\n",
    "print(2)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
```

**Comment by vidartf** [comment]
> I don't think it has anything two do with git. If I use nbdiff directly, I get the same problem.

Nbdiff calls out to git for formatting the diff, if it is available. However, it seems as if this does not work entirely as intended. I can reproduce this on Windows, so it seems to be a platform-independent problem.

I won't really have time to properly debug this for a while, so consider setting those flags to false as workaround for now. If you want to contribute, you can save the content of the cell as two text files (e.g. `a.txt` and `b.txt`), and try to find a way to make git diff them as you want. Currently the command used is equivalent to `git diff --no-index --color-words a.txt b.txt`, which gives the following output:

```diff
diff --git "a/.\\a.txt" "b/.\\b.txt"
index d86ac44..b1bd67a 100644
--- "a/.\\a.txt"
+++ "b/.\\b.txt"
@@ -2,5 +2,5 @@ with open("numbers.txt") as f:
    l = []
    for line in f:
        l.append(float(line.strip()))
l.sort()
l.reverse()
```

Note: Removing the `--color-words` options seem to make the output similar to that of not using git, so maybe we will have to drop the word-based diffing display.
