### ISSUE TITLE
Webdiff is not displaying side by side

### ISSUE THREAD

**Issue by LindyBalboa** [jupyter/nbdime#299]
System: Up to date Arch
Jupyter: 5.0.0
nbdime: 0.3.0
Firefox: 54.0.1
Chromium: 60.0.3112.78 

command to open:
```
nbdiff-web HEAD HEAD~1
```

![image](https://user-images.githubusercontent.com/20605205/28828759-065e34c6-76d2-11e7-86b9-60eef5cbb676.png)

**Comment by vidartf** [comment]
Thanks for the report. I'll have a look at implementing this. For reference, there are two points to this:
 1. The content of the cells are different enough that the differ does not recognize the remote one as a patch of the local one. Instead it registers it as a delete/add pair. This is a general problem for diffing small cells, so this cannot easily be fixed (you could end up aligning cells that should not be considered similar).
 2. Currently, all add/remove cell sequences are shown staggered like this, with the added cells first, and then the deleted cells. A better approach is to show them side by side as suggested, which makes this a layout issue. This is what should be implemented.

**Comment by LindyBalboa** [comment]
That is interesting to know. I tried this again with the following result. I'm still getting the plots staggered:

![image](https://user-images.githubusercontent.com/20605205/28867983-4725af1a-7778-11e7-89aa-054465a17873.png)

**Comment by vidartf** [comment]
Yes, it currently has no way of comparing plots (they are just binary blobs), so those will always become add/remove pairs. They should preferably still be shown side by side as mentioned for the cells above (layout issue).

**Comment by jbwhit** [comment]
Then what's going on in the documentation where something like this is explicitly shown as a side-by-side comparison in the docs:

![example](https://raw.githubusercontent.com/jupyter/nbdime/master/docs/source/images/nbdiff-web.png)

**Comment by vidartf** [comment]
@jbwhit I think that screenshot is from an older version where outputs where treated very simplistically.
