### ISSUE TITLE
point_conversion_form_t

### ISSUE THREAD

**Issue by mroswell** [jupyter/nbdime#302]
```
$ nbdime config-git --enable --global
/Users/m/anaconda/lib/python2.7/site-packages/cffi/model.py:525: UserWarning: 'point_conversion_form_t' has no values explicitly defined; guessing that it is equivalent to 'unsigned int'
  % self._get_c_name())
m (master *) analysis $ git diff notebook.ipynb
/Users/m/anaconda/lib/python2.7/site-packages/cffi/model.py:525: UserWarning: 'point_conversion_form_t' has no values explicitly defined; guessing that it is equivalent to 'unsigned int'
  % self._get_c_name())
```
I guess I need to find my global git configuration file somewhere to turn this off. 

So this is a two-parter:
1. How to disable nbdime for git (until it works)?
2. How to make it actually work?

**Comment by mroswell** [comment]
Looks like I need to remove these lines from ~/.gitconfig
```
[diff "jupyternotebook"]
        command = git-nbdiffdriver diff
[merge "jupyternotebook"]
        driver = git-nbmergedriver merge %O %A %B %L %P
        name = jupyter notebook merge driver
[difftool "nbdime"]
        cmd = git-nbdifftool diff \"$LOCAL\" \"$REMOTE\"
[difftool]
        prompt = false
[mergetool "nbdime"]
        cmd = git-nbmergetool merge \"$BASE\" \"$LOCAL\" \"$REMOTE\" \"$MERGED\"
[mergetool]
        prompt = false
```

**Comment by mroswell** [comment]
Looks like I need to remove these from ~/.gitconfig. Is that right? Especially not sure about the first 5 lines.
```
[diff "jupyternotebook"]
        command = git-nbdiffdriver diff
[merge "jupyternotebook"]
        driver = git-nbmergedriver merge %O %A %B %L %P
        name = jupyter notebook merge driver
[difftool "nbdime"]
        cmd = git-nbdifftool diff \"$LOCAL\" \"$REMOTE\"
[difftool]
        prompt = false
[mergetool "nbdime"]
        cmd = git-nbmergetool merge \"$BASE\" \"$LOCAL\" \"$REMOTE\" \"$MERGED\"
[mergetool]
        prompt = false
```

**Comment by vidartf** [comment]
1. Glad you figured out how to disable it. If not, all CLI config commands take either `--enable` or `--disable`. The `--disable` flag should disable nbdime similar to what you did (i.e. `nbdime config-git --disable --global`).

**Comment by vidartf** [comment]
Regarding point 2:
- Is this just an annoying warning, or is it actually preventing nbdime from working?
- This warning might be from an outdated dependency. Could you share the output of `pip list` and `conda list` if applicable?

**Comment by vidartf** [comment]
@mroswell Were you able to get it to work?

**Comment by vidartf** [comment]
Closing due to lack of feedback. Feel free to reopen/comment if anyone has further information to share here.
