### ISSUE TITLE
-S, -O, -A, -M flags being ignored

### ISSUE THREAD

**Issue by polygonica** [jupyter/nbdime#313]
Command run: 
nbdiff HEAD notebook.ipynb -S -O -A -M

Expected output:
nothing

Actual output:
metadata, run counts, outputs, code

(I'm running a pip install of nbdime)

**Comment by vidartf** [comment]
This should be fixed on master. A new release should be expected soon.

C.f. #290, #303, #305.

Note: Ignoring everything is a corner case that is not tested for, and might fail. Do you have a realistic use case?

**Comment by polygonica** [comment]
Sorry, I was being too brief. The flags were, individually, not working either.

**Comment by vidartf** [comment]
Previous fixes now released in 0.4.0.
