### ISSUE TITLE
Make merge produce conflicts on adjacent changes

### ISSUE THREAD

**Issue by martinal** [jupyter/nbdime#32]
Currently, merging these three source cells:

base:

```
def foo(x, y):
    z = x * y
    return z
long line with minor change
```

local:

```
def foo(x, y):
    z = x * y
    return z
long line with minor change L
```

remote:

```
def foo(x, y):
    z = x * y
    return z
long line with minor change R
```

results in both diffs agreeing on removing the last line, and each diff inserting a new line, with the end result:

```
def foo(x, y):
    z = x * y
    return z
long line with minor change L
long line with minor change R
```

I think this is too forgiving, in cases such as this there should be a conflict. @minrk agree?

**Comment by minrk** [comment]
Yeah, that should probably conflict.

**Comment by martinal** [comment]
Note that this is similar to your import statements merge annoyance, and will make this a conflict:

base:
```
import foo
import bar
```

local:
```
import foo
import fizz
```

remote:
```
import foo
import buzz
```

Anyway, I have a sketch of how to handle the merge better.

**Comment by martinal** [comment]
https://github.com/jupyter/nbdime/pull/38 should fix some cases but more cases remain, e.g. inserts after a deleted range are currently accepted but probably should not be.

**Comment by martinal** [comment]
Seems to be solved now:
```
martinal:nbdime/nbdime/tests/files (add-merge-tests=) $ nbmerge b.ipynb l.ipynb r.ipynb | nbshow -s -
[W nbmergeapp:47] Conflicts occured during merge operation.
code cell 0:
  source:
    def foo(x, y):
        z = x * y
        return z
    <<<<<<< local
    long line with minor change L
    =======
    long line with minor change R
    >>>>>>> remote
```
