### ISSUE TITLE
Metadata in diff

### ISSUE THREAD

**Issue by sbalian** [jupyter/nbdime#324]
Is there a way to exclude lines such as the ones below from the `nbdiff` output?

```
## added /cells/11/metadata/collapsed:
+  True

## added /cells/12/metadata/collapsed:
+  True

## added /cells/15/metadata/collapsed:
+  True

## added /cells/18/metadata/collapsed:
+  True

## added /cells/28/metadata/collapsed:
+  True
```

**Comment by vidartf** [comment]
You should be able to filter all metadata with the `-M`/`--ignore-metadata` flag (see http://nbdime.readthedocs.io/en/stable/cli.html#common-diff-options for full explanation). There is however no way to filter specific keys from the CLI. If you need such fine control you will need call it as a library.

**Comment by vidartf** [comment]
Closing this as answered.
