### ISSUE TITLE
Odd alignment issue in html view

### ISSUE THREAD

**Issue by fperez** [jupyter/nbdime#325]
Is this alignment expected?

![image](https://user-images.githubusercontent.com/57394/32976564-211604be-cbce-11e7-8471-2b112e528fc6.png)

This corresponds to [this diff](https://github.com/pbstark/S157F17/pull/1/files). I didn't expect the first cell to be right-aligned like that, squishing both old and new into the right-hand side of the screen.

**Comment by vidartf** [comment]
Definitively shouldn't be like that. We recently made some changes to the CSS, which is likely the culprit. I'll look into it on Monday. Just to be on the safe side: which brower(s) were this with?

**Comment by vidartf** [comment]
I've PRed a fix in #326. Thanks for including the diff in question, it made it really easy to reproduce 👍
