### ISSUE TITLE
Add wrapper script for git mergetool configuration

### ISSUE THREAD

**Issue by martinal** [jupyter/nbdime#33]
For git mergetool to trigger nbmerge only for ipynb files, it seems we need to make a wrapper script that is invoked for all filetypes, checks the filetype, and forwards to another tool if it's not ours to merge.

A suggestion that could work with some modifications is here:
https://gist.github.com/elsevers/11349227

**Comment by minrk** [comment]
This is what we already do in the difftool, so I think the same approach should work.

**Comment by martinal** [comment]
Can we close this now?

**Comment by vidartf** [comment]
I think we can say that it has been superseded by #88.
