### ISSUE TITLE
Metadata comparison should be optional

### ISSUE THREAD

**Issue by xtotdam** [jupyter/nbdime#338]
Metadata comparison should be optional just like hiding unchanged cells.
The following situation is common:
  * `ExecuteTime` Jupyter addon writes last execution time and date into metadata
  * Cells are being executed thus execution time and date updates
  * We get many 'changed' cells that are identical

**Comment by vidartf** [comment]
There are flags for the CLI commands to ignore metadata/outputs etc. These also work for the web views (see documentation). That being said there is currently work in progress to make this more powerful, and configurable (meaning you can set defaults). This work is being done in between other higher priority tasks though, so I have no good estimate for when it will land, so for now the existing command flags will have to do.

**Comment by xtotdam** [comment]
Oh
Thank you for pointing to it!

**Comment by vidartf** [comment]
> That being said there is currently work in progress to make this more powerful, and configurable (meaning you can set defaults).

This has now been implemented via #355. See the [latest docs](http://nbdime.readthedocs.io/en/latest/config.html) (feature still unreleased) for usage explanation. As such, I'm closing this issue.
