### ISSUE TITLE
Autoresolve doesn't shift conflict indices

### ISSUE THREAD

**Issue by martinal** [jupyter/nbdime#34]
Indices (keys) in the conflict diffs returned from autoresolve must be shifted to reflect edits to the document. Probably best to make autoresolve return (newdocument, localconflicts, remoteconflicts) like merge does instead of (resolvedconflicts, localconflicts, remoteconflicts) as it does now.

**Comment by martinal** [comment]
TODO: Test better if https://github.com/jupyter/nbdime/pull/38 fixed this completely.

**Comment by vidartf** [comment]
Fixed, as merge decisions are now returned in an order such that deeper paths are considered first. See #76.
