### ISSUE TITLE
Make autoresolve accept cell inserts from both sides

### ISSUE THREAD

**Issue by martinal** [jupyter/nbdime#36]
While inserting items at the same location in a list in general is suspicious and should be a conflict, for cells we can arguably allow inserting cells at the same location and before and after cells with conflicting edits. This is because a 'cell' is a more 'isolated component' than e.g. source lines. Since the merge algorithm is generic (notebook-independent), this is probably easiest implemented in autoresolve.

**Comment by vidartf** [comment]
Current solution in master is to diff the lists in the two sides in order to identify:
   - Common sub sequences (including identical, aligned inserts)
   - One-sided inserts
   - Conflicted inserts

I judge that to be a good enough solution to close this for now.
