### ISSUE TITLE
Web view when running git diff 

### ISSUE THREAD

**Issue by idoDavid** [jupyter/nbdime#361]
Hi,

Is it possible to config git in such a way that running git diff on a modified notebook will open the two versions on the browser? 

It's not a must, I don't have a problem to also run the `nbdiff-web [ref [ref]]` as recommended in the doc, but what are the ref [ref] in this case? wasn't able to figure it out. So if I changed notebook a.ipnb, how do I compare it to the remote version of itself via nbdiff-web command? 

Not clear, can you elaborate?

**Comment by vidartf** [comment]
> what are the ref [ref] in this case?

This means git reference, like a branch name, a checksum, or things like `HEAD~3`. It should work the same as `git diff ...` does, e.g. `git diff master branchA`. Called `<commit>` in the [git diff docs](https://git-scm.com/docs/git-diff).

> if I changed notebook a.ipnb, how do I compare it to the remote version of itself via nbdiff-web command?

There are different ways:

- `nbdiff-web remote a.ipynb`: Compares current working directory version of a.ipynb to that in branch "remote".
- `nbdiff-web HEAD remote a.ipynb`: Compares a.ipynb in the *current commit* to that in branch "remote".
- `nbdiff-web local remote a.ipynb`: Compares a.ipynb in branch "local" to that in "remote".

For reference, `nbdiff-web a.ipynb` compares the file on disk to the current commit (HEAD).

If a.ipynb is the only notebook you changed, you don't have to specify the filename.

**Comment by idoDavid** [comment]
@vidartf thanks! that's super helpful!

**Comment by vidartf** [comment]
Thanks for asking about what is unclear 👍 I've tried to make the relevant sections of the docs clearer.
