### ISSUE TITLE
Conflict will be removed when merging different branches

### ISSUE THREAD

**Issue by haolee21** [jupyter/nbdime#368]
I am not so sure did I use it correctly.
Currently if I just use 
` 
git merge master beta
`
all conflict will get removed, I wonder is it a bug or I just use it wrong.
(p.s. I believe I have set .gitconfig and .gitattributes correctly)

**Comment by vidartf** [comment]
I'm struggling to understand the specifics of this issue. Would you mind giving some more details about what you are doing? Even better, could you share an example of a conflict you would expect between master and beta that gets removed?

**Comment by vidartf** [comment]
Could you share the two versions of the notebooks (from beta and master, and possibly their common base)? This way I can debug the code.

**Comment by vidartf** [comment]
Are you able to get this to work with the latest version of nbdime (1.0.0)?
