### ISSUE TITLE
nbmerge not able to create .ipynb

### ISSUE THREAD

**Issue by chitwankaudan** [jupyter/nbdime#379]
I'm getting a invalid JSON error when using nbmerge. Seems like nbmerge isn't correctly storing the conflict markers inside the notebook JSON. The merge errors out and merged.ipynb is just an empty file.

![image](https://user-images.githubusercontent.com/25287662/41152972-f8bd790c-6b32-11e8-8084-4af95fd8da33.png)
 
Git won't let me upload .ipynb here so I've converted them to .txt, you can convert them back once download. 
[base_test.ipynb.txt](https://github.com/jupyter/nbdime/files/2083985/base_test.ipynb.txt)
[local_test.ipynb.txt](https://github.com/jupyter/nbdime/files/2083992/local_test.ipynb.txt)
[remote_test.ipynb.txt](https://github.com/jupyter/nbdime/files/2083993/remote_test.ipynb.txt)

OR here are screenshots of the above files:
base_test.ipynb
![image](https://user-images.githubusercontent.com/25287662/41153781-6d88936e-6b35-11e8-80fa-d2f6c07f0025.png)

local_test.ipynb
![image](https://user-images.githubusercontent.com/25287662/41153859-b1c041c6-6b35-11e8-8db4-51be2391c728.png)

remote_test.ipynb
![image](https://user-images.githubusercontent.com/25287662/41153865-ba5b0ffa-6b35-11e8-8d41-65422de4a8f3.png)

Below is the relevant package, system, machine info:

![image](https://user-images.githubusercontent.com/25287662/41154034-5fc005a4-6b36-11e8-9bdd-63c4e542d8d1.png)

Why is this happening?

**Comment by vidartf** [comment]
Thanks a lot for the very detailed report! It made it very easy to reproduce the issue. A proposed fix with tests are available in #380.

**Comment by chitwankaudan** [comment]
Thank you! :)

**Comment by vidartf** [comment]
Merged, hoping to do a patch release on Monday! (feel free to ping here if I forget)

**Comment by vidartf** [comment]
Released as 1.0.1
