### ISSUE TITLE
custom config is ignored by nbdime when used via jupyter extension

### ISSUE THREAD

**Issue by stas00** [jupyter/nbdime#383]
**Problem: using nbdime-1.0.0 I have trouble telling it to ignore all diffs but code cells when run via notebook.**

1) first the docs are broken:

http://nbdime.readthedocs.io/en/stable/config.html

the given examples fail to validate via `nbdime --config` - True/False have to be true/false to validate.

2) second it doesn't seem like there is any validation to what user config file includes, you can write anything that's valid json format and it'll use it. You have no way of telling whether you are doing it right or not.

3) I tried many many many different combinations to get my custom configured nbdime to work as an extension from jupyter notebook, but my configuration is completely ignored.

What I'm trying to configure is for it to ignore all attachments, outputs and metadata, I tried many versions of `~/.jupyter/nbdime_config.json`. The latest incarnation is:

```
{
  "GitDiff": {
    "Ignore": {
      "/cells/*/outputs": true,
      "/cells/*/attachments": true,
      "/cells/*/metadata": true
    }
  },
  "Diff": {
    "Ignore": {
      "/cells/*/outputs": true,
      "/cells/*/attachments": true,
      "/cells/*/metadata": true
    }
  },
  "WebTool": {
    "Ignore": {
      "/cells/*/outputs": true,
      "/cells/*/attachments": true,
      "/cells/*/metadata": true
    }
  },
  "Web": {
    "Ignore": {
      "/cells/*/outputs": true,
      "/cells/*/attachments": true,
      "/cells/*/metadata": true
    }
  }
}

```

I also tried setting:

`"ignore_transients": true`

to no avail.

I can see that nbdime picks my changes via `nbdime --config`

But when I run `http://localhost:8888/nbdime/git-difftool?base=test.ipynb` invoked via the git diff button in the notebook. I get all the diffs. I want just the code cell diffs.

Thank you.

nbdime-1.0.0
{'commit_hash': '7f10f7bb3',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python3.6/dist-packages/IPython',
 'ipython_version': '6.4.0',
 'os_name': 'posix',
 'platform': 'Linux-4.4.0-127-generic-x86_64-with-Ubuntu-16.04-xenial',
 'sys_executable': '/usr/bin/python3.6',
 'sys_platform': 'linux',
 'sys_version': '3.6.5 (default, Mar 29 2018, 03:28:50) \n[GCC 5.4.0 20160609]'}

**Comment by vidartf** [comment]
Hi, and thanks for the report! The documentation is was a remnant from the initial draft when both the python and json configuration styles were allowed, which I guess was not translated properly when we switched to a pure JSON version. The ignores were not picked up, as the configuration was previously only picked up on the entry points nbdime owned. I agree it should be supported for frontends as well!

A proposed fix is available in #384. Does the outlined changes (see docs bit) make sense?

**Comment by vidartf** [comment]
@stas00 I merged the PR, but if you have any input (even minor ones) feel free to comment here / on the PR and I'll do a quick followup! I want to get a patch release out today for #379, and I want to include this if possible.

**Comment by stas00** [comment]
Thank you, vidartf, 1.0.1 made a difference! Now the custom config is being applied!

Could you please add to the docs to use GitDiff entry for jupyter notebook's nbdime extension use?

The current docs do include Extension:

GitDiff
    Options to git diff commands (NbDiff, NbDiffWeb, NbDiffDriver, NbDiffTool, Extension)

But so does:

Diff
    Options to diffing commands (NbDiff, NbDiffWeb, NbDiffDriver, NbDiffTool, Extension).

and it's only GitDiff that is needed. Perhaps we can also work out an example that can be copy-n-pasted by the users without needing to figure it out. Currently I'm using:

{
  "GitDiff": {
    "Ignore": {
      "/cells/*/outputs": true,
      "/cells/*/attachments": true,
      "/cells/*/metadata": true
    }
  }

}

**Comment by vidartf** [comment]
You can use the section name `Extension` for your config instead of `GitDiff`:

```json
{
  "GitDiff": {
    "Ignore": {
      "/cells/*/outputs": true,
      "/cells/*/attachments": true,
      "/cells/*/metadata": true
    }
  }
}
```

The sections are for things that configure several entry points.

**Comment by stas00** [comment]
Excellent, thank you, Vidar.

please kindly add this to the docs so others don't need to figure it out.
As of this writing Extension is not listed in Sections at https://nbdime.readthedocs.io/en/stable/config.html
and an example would be handy too.
Thank you!

**Comment by vidartf** [comment]
#390 has some improvements to the docs, hopefully this should make it more clear!
