### ISSUE TITLE
nbextensions thinks nbdime is incompatible

### ISSUE THREAD

**Issue by stas00** [jupyter/nbdime#387]
nbdime-1.0.1

http://localhost:8888/tree?#nbextensions_configurator

![nbdime-2](https://user-images.githubusercontent.com/10676103/41249082-dba0d7e2-6d67-11e8-90e7-e44a90d9cd10.png)
```

% jupyter  nbextension list
Known nbextensions:
[...]
  config dir: /usr/local/etc/jupyter/nbconfig
    notebook section
      nbdime/extension  enabled
      - Validating: problems found:
        - require?  X nbdime/extension

jupyter serverextension list
config dir: /home/stas/.jupyter
[...]
    nbdime  enabled
    - Validating...
      nbdime 1.0.1 OK
config dir: /usr/local/etc/jupyter
    nbdime  enabled
    - Validating...
      nbdime 1.0.1 OK


```

Thank you.

**Comment by vidartf** [comment]
Thanks for the report. How was this installed? I see there are two server extension configurations, which should not be the case after a fresh install. You might want to uninstall nbdime completely (run `pip uninstall nbdime` multiple times, and clear out any reference to nbdime in directories given by `jupyter --paths`). A fresh install should then work as intended.

**Comment by stas00** [comment]
I did a complete cleanup server-side and user-side to no avail. 

I don't know enough about how nb install process works, but I think nbdime-jupyterlab extension gets registered but doesn't get installed. After re-installing the python package:

`pip3 install -U nbdime`

I see:

```
/usr/local/share/jupyter# find

./lab/extensions/nbdime-jupyterlab-0.3.0.tgz
./nbextensions/nbdime/index.js
```

and `jupyter nbextension list` complains about:

```
  config dir: /usr/local/etc/jupyter/nbconfig
    notebook section
      nbdime/extension  enabled
      - Validating: problems found:
        - require?  X nbdime/extension
```
shouldn't nbdime-jupyterlab-0.3.0.tgz be unpacked and installed somewhere for nbdime/extension to work?

The main part validates just fine:

```
      nbdime/index  enabled
      - Validating: OK
```
The loading of the problematic part happens here:
```
/usr/local/etc/jupyter/nbconfig/notebook.d/nbdime.json:  "load_extensions": {
/usr/local/etc/jupyter/nbconfig/notebook.d/nbdime.json:    "nbdime/extension": true
```

So where on the filesystem is it looking for  "`nbdime/extension`"? and why the tgz extension package name is `nbdime-jupyterlab` - please help me to find out what and where is it looking for when it invokes load_extensions and then perhaps we can see what's missing.

Steps I did:


```
sudo pip3 uninstall nbdime
sudo jupyter nbextension disable nbdime --system --py
sudo jupyter nbextension uninstall nbdime --system --py
sudo pip3 install -U nbdime
sudo jupyter nbextension install nbdime --system --py
sudo jupyter nbextension enable  nbdime --system --py

# then as user 
jupyter nbextension disable nbdime --user --py 
jupyter nbextension uninstall nbdime --user --py
jupyter nbextension install nbdime --user --py
jupyter nbextension enable  nbdime --user --py
```

**Comment by vidartf** [comment]
Thanks, I was finally able to track this down. The `nbdime/extension` config is incorrect, and comes from the install (data file). I'll do a patch release for that.

As a side note, the lab extension should not show up in `jupyter nbextension list`, but in `jupyter labextension list`. I don't see any errors with the config here.
