### ISSUE TITLE
nbdime+ jupyter: select/copy-n-paste doesn't work for code cells

### ISSUE THREAD

**Issue by stas00** [jupyter/nbdime#392]
I've stumbled upon a very strange problem. When diff is shown via jupyter - the code cells in the diff can't be selected/copied to be pasted somewhere else. This defeats the purpose :(

I saved the html and reduced the problematic html to:

`<div class="CodeMirror-scroll" tabindex="-1" draggable="true">`

if draggable is set to false it works (the text is selectable/copyable), with true it doesn't.

everything else on the page can be selected/copied just fine.

I had to save the diff as html and to run:

`perl -pi -e 's|draggable="true"|draggable="false"|' diff.html`

and then I was able to extract the code diff I was after.

this is with nbdime-1.0.1 - same behavior with both firefox and chrome on ubuntu.

Thank you.

**Comment by vidartf** [comment]
> When diff is shown via jupyter

Did you mean jupyter lab?

**Comment by vidartf** [comment]
I've been trying with both jupyter lab and jupyter notebook, and I am not able to reproduce this (cells for diff should not be draggable at all). Could you describe the steps to reproduce this in more detail?

**Comment by stas00** [comment]
To clarify, I am having this issue with Jupyter notebook, e.g.:

http://localhost:8888/nbdime/git-difftool?base=fastai%2Fcourses%2Fdl1%2Flesson3-rossman.ipynb

I never said the cells are draggable. They aren't. It's the CSS class `CodeMirror-scroll` that says that.

Are you able to copy-n-paste from the code cell `http://localhost:8888/nbdime/git-difftool?base=...`? It works for any other content in that git-difftool output, but not code cells.

**Comment by vidartf** [comment]
It seems to be caused by this issue:
https://github.com/codemirror/CodeMirror/issues/2568

I'll have a look if the workaround outlined there will work for nbdime (there was some issue with editors screwing up keyboard tabbing).

**Comment by vidartf** [comment]
Ref: Workaround for original tabbing issue: https://github.com/codemirror/CodeMirror/issues/5444

**Comment by vidartf** [comment]
@stas00 After re-installing, you will have to reinstall the nbextension (`jupyter nbextension install ...`). Alternatively, you can run `jupyter nbextension install --sym-link ...` to have the nbextension build output folder be symlinked to the correct `share` subfolder folder. I'll provide more details in the update to the dev docs.

**Comment by vidartf** [comment]
See #397 for dev install description.

**Comment by stas00** [comment]
This ticket is still unresolved.

I did some more investigation and your change did have an impact on "Export diff" - the saved output no longer has those draggable divs - and the code cells can be selected and copied from. Excellent. Thank you!

But the direct output of [git nbdiff] still has this problem. Copy-n-paste of the code cells still doesn't work from http://localhost:8888/nbdime/git-difftool?base=...

**Comment by vidartf** [comment]
> But the direct output of [git nbdiff] still has this problem.

Oh, I'm sorry, I only tested it for the labextension, which now works. I assumed that since it had been fixed there, it was fixed everywhere. Very strange...

**Comment by vidartf** [comment]
It was due to a bookkeeping issue, so that the new code was not propagated to the standalone web diff code. Fix in #399.

**Comment by stas00** [comment]
I confirm this to be fixed in jupyter notebook. Thank you, Vidar.
