### ISSUE TITLE
git mergetool web save button does not work?

### ISSUE THREAD

**Issue by noklam** [jupyter/nbdime#404]
I try to solve my merge conflicts with the web mergetools, saving a new files seems working fine, but the save button has no response. No matter how I do it, if I click save and then close tool, git will tell me there is no changes.

![image](https://user-images.githubusercontent.com/18221871/42883934-90d08002-8acf-11e8-880b-f470efb9f385.png)

**Comment by vidartf** [comment]
Thanks for the report! The mergetool is unfortunately the least mature part of nbdime, but hopefully reports like this can help it mature. Are there any error messages in the web browser console? Also, which version of nbdime are you using (`nbdime --version`)? Maybe more importantly here, what kind of conflict(s) were you having (e.g. cell edit vs deletion; conflicting cell edits; conflicting outputs; conflicting metadata; etc.)? If you wouldn't mind sharing the notebooks in question, it would be a lot easier for me to reproduce the issue!

**Comment by noklam** [comment]
Which way is preferred if mergetool is least mature at this point? I will provide more information when I get the computer that I was using.
From what I have remember it was conflicting cell edit, which I have a conflicting edit in my remote repo and my local repo, it is simple conflict like a=3(previous), a=4(local), a=5(remote)  something similar as this.

https://github.com/noklam/nbdime/blob/master/notebook1.ipynb (This was the remote repo that I pull, I have a local version which has some conflicting edit (I intended to do so to test this tool.)

**Comment by vidartf** [comment]
> Which way is preferred if mergetool is least mature at this point?

The easiest way is to simply open the conflicted notebook using the normal notebook editor. It should contain markers (`<<<<<<<` and `>>>>>>>`) indicating conflicts. After editing the notebook to the final state that you want, you can run `git add <path to notebook>` and `git merge --continue` (or for older versions of git, use `git commit`).

I'll look into the notebook you linked, but preferably I would also need to know which changes were made (the local changes).

**Comment by vidartf** [comment]
I was able to reproduce the issue, and I've posted a PR fixing the problem (+ a few other styling issues) in #422.

**Comment by noklam** [comment]
Thanks for fixing this.
