### ISSUE TITLE
Adding jupyterlab-extension topic to project description?

### ISSUE THREAD

**Issue by BoPeng** [jupyter/nbdime#412]
I was searching for a jupyter lab extension for diffing notebook and could be find it, then I found nbdime and noticed that it has a lab extension. I would suggest that you add a " jupyterlab-extension" topic to the description so that this project can be found through https://github.com/topics/jupyterlab-extension . Thanks.

**Comment by vidartf** [comment]
Thanks, I added a bunch of topics!
