### ISSUE TITLE
[Git integration]: Git merge strategy options do not propagate to nbdime

### ISSUE THREAD

**Issue by ZmG** [jupyter/nbdime#414]
My goal is to resolve conflicts in notebooks in favor of the remote or local changes using the git interface. 

Currently, it appears that git merge strategy flags are not mapped to nbdime merge actions listed in the documentation:
<img width="717" alt="screen shot 2018-08-07 at 16 51 05" src="https://user-images.githubusercontent.com/4634239/43808498-30b5a48e-9a62-11e8-8ffc-8ff0bc95ccd1.png">

 For example, 
`git pull --strategy', 'recursive', '--strategy-option' ours` results in a conflict as opposed to resolving the conflict using my local changes. 

Is there any plan to support that?

**Comment by vidartf** [comment]
This is an issue of git not passing this information on to merge drivers. See the [git documentation](https://git-scm.com/docs/gitattributes#_performing_a_three_way_merge) for more details (the "Defining a custom merge driver" sub-section). As such, there's not really anything that can be done easily. One possible solution would be to let the merge strategy be configurable by a env variable (e.g. `NBDIME_MERGE_STRATEGY`), but this would be a workaround no matter how it is solved.

FYI: The corresponding flag for nbdime's merge commands are `--merge-strategy use-local`

**Comment by ZmG** [comment]
@vidartf  Thanks. It seems that this is not nbdime issue so closing. 

I ended up writing a very simple custom merge driver. Basically, a wrapper shell script that passes the values `use-local` or `use-remote` for the `--merge-strategy` to nbmdime based on the value of a custom git config option.
