### ISSUE TITLE
Incompatible extension?

### ISSUE THREAD

**Issue by darribas** [jupyter/nbdime#419]
Hello,

When building [this container](https://github.com/darribas/gds_env/blob/master/Dockerfile), which builds on the official [`minimal-notebook`](https://github.com/jupyter/docker-stacks/blob/master/minimal-notebook/Dockerfile), I run into compatibility issues with the `nbdime` extension:

```shell
jovyan@ce138040252d:~$ jupyter labextension list
JupyterLab v0.34.0
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.37.2  enabled  OK
@jupyterlab/hub-extension
        @jupyterlab/hub-extension v0.11.0  enabled  OK
jupyter-leaflet
        jupyter-leaflet v0.9.0  enabled  OK
nbdime-jupyterlab
        nbdime-jupyterlab v0.4.0  enabled   X

"nbdime-jupyterlab@0.4.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab             Extension        Package
>=0.18.2 <0.19.0       >=0.17.0 <0.18.0 @jupyterlab/apputils
>=0.18.2 <0.19.0       >=0.17.0 <0.18.0 @jupyterlab/notebook
>=0.18.2 <0.19.0       >=0.17.0 <0.18.0 @jupyterlab/rendermime


jovyan@ce138040252d:~$
```

It seems there is something on the Lab components that are not up to parr with what `nbdime`, but can't figure out how to fix it. Any suggestions? Thank you very much in advance.

**Comment by jamesmyatt** [comment]
The issue is that the nbdime extension hasn't been updated for the latest jupyterlab release.

Does anyone know when this is planned to happen?

**Comment by vidartf** [comment]
I have a deadline today, so I'll try to get the extension updated and released after that. The latest version of lab has some changes that require changes to the code and styling.

**Comment by jamesmyatt** [comment]
Thanks @vidartf

**Comment by darribas** [comment]
Thank you very much for this! How can I install the updated version? Is it available through `pip` or `conda`?

**Comment by vidartf** [comment]
Its not on pip/conda yet, as I want to grt some more fixes in there before release, but you can update with `jupyter labextension update nbdime-jupyterlab`, since there were no changes to the server side of things.
