### ISSUE TITLE
How can I use `nbdime` with interactive git diffs?

### ISSUE THREAD

**Issue by joelostblom** [jupyter/nbdime#423]
How can I use `nbdime` with interactive git diffs such as the output from `git add -p`? I tried adding 

```
[interactive]
    diffFilter = git-nbdiffdriver diff
```
to my `~/.gitconfig`, but running `git add -p` fails with the error message 

```
git-nbdiffdriver diff: error: the following arguments are required: path
```
I currently have the following in my `~/.gitconfig`:

```
[diff "jupyternotebook"]
    command = git-nbdiffdriver diff
[merge "jupyternotebook"]
    driver = git-nbmergedriver merge %O %A %B %L %P
    name = jupyter notebook merge driver
[difftool "nbdime"]
    cmd = git-nbdifftool diff \"$LOCAL\" \"$REMOTE\"
[difftool]
    prompt = false
[mergetool "nbdime"]
    cmd = git-nbmergetool merge \"$BASE\" \"$LOCAL\" \"$REMOTE\" \"$MERGED\"
[mergetool]
    prompt = false
```

**Comment by joelostblom** [comment]
I guess another way to phrase this question is if there is any way to have `git-nbdiffdriver diff` read from `stdin`, since it seems like the output is piped to the command specified by `interactive.diffFilter`:

```
     interactive.diffFilter
           When an interactive command (such as git add --patch) shows a colorized diff, git will pipe the diff through the shell command defined by this configuration variable. The
           command may mark up the diff further for human consumption, provided that it retains a one-to-one correspondence with the lines in the original diff. Defaults to disabled (no
           filtering).
```

**Comment by vidartf** [comment]
An interesting case, but I do not think git allows for using nbdime here. As you point out, the relevant extension point is `interactive.diffFilter`. However, this command only receives the output that would normally be printed by the `git add -p` command, i.e. the formatted chunk. There is another constraint:

> [...] provided that it retains a one-to-one correspondence with the lines in the original diff

Given this, I find it hard to see what nbdime should do. The only alternative I see is to create your own entry point (command) that you run. The application would present the diff, and allow you to choose the various parts interactively. Then, those changes would need to be converted to a standard git patch, which could then be staged with `git apply --cached --ignore-whitespace` (what `git gui` does). If you want to create such an application, I'd be happy to help out, but I don't think I can entirely take it upon myself.

**Comment by vidartf** [comment]
Closing as no applicable actions for nbdime.

**Comment by joelostblom** [comment]
Thanks for your suggestions @vidartf and for offering to help out working on
a solution to this. I understand if this is outside the scope for `nbdime`, and
I feared that the 1 to 1 correspondence would be an issue.

It is mostly changes in images/plots and if many cell execution numbers are
altered that it becomes a bit cumbersome with `git add -p`, I will see if I can
adapt my workflow around this somehow. If not, I will look into another
solution and might ping you here again and see if you are interested.

**Comment by vidartf** [comment]
You might have more success with a git filter like nbstripout, e.g. by keeping execution numbers out of the repo (`null` value).

**Comment by joelostblom** [comment]
I just noticed that `diff-so-fancy` have been able to get their particular git diff format to work even with interactive diffs https://github.com/so-fancy/diff-so-fancy/issues/35#issuecomment-776870877 (and they previously had the same issues discussed above with the 1-to-1 correspondence). I am not sure how their implementation works but thought it would be worth mentioning in case someone stumbles over this and is interested in trying to implement it.
