### ISSUE TITLE
Why is the last version available in pypi.org 1.0.2?

### ISSUE THREAD

**Issue by alealv** [jupyter/nbdime#425]
Why is the last version available in pypi.org 1.0.2?
I've checked that you've tagged version 3.1.0 but it's not available with pip install.

Despite that, I've tried this version but I've had no luck with the jupyter extension when using jupter lab

**Comment by vidartf** [comment]
The 3.1.0 tag is for the JS package that is used for building the web views. The tags of the python package are without a prefix. 1.0.2 is the latest version of the Python package.

To get the lab extension working, you should follow the steps here: https://nbdime.readthedocs.io/en/latest/extensions.html#installation  If you are still having issues, here are some debug outputs that could help narrow the problem down:
- `jupyter serverextension list`
- `jupyter labextension list`
- The server log from running jupyter lab
- The output in the browser console when running jupyter lab

**Comment by alealv** [comment]
Thanks for your fast answer. 
It seems that my Jupyterlab packages versions were not compatible with nbdime. I've updated it and now it's working.

JupyterLab v0.31.12
Known labextensions:
   app dir: /home/alejandro/.local/share/jupyter/lab
nbdime-jupyterlab
        nbdime-jupyterlab v0.4.0  enabled   X

"nbdime-jupyterlab@0.4.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab             Extension            Package
>=0.15.4-0 <0.16.0-0   >=0.17.0-0 <0.18.0-0 @jupyterlab/rendermime
>=1.1.4-0 <2.0.0-0     >=3.0.0-0 <4.0.0-0   @jupyterlab/services
>=1.0.10-0 <2.0.0-0    >=2.0.0-0 <3.0.0-0   @jupyterlab/coreutils
>=0.15.7-0 <0.16.0-0   >=0.17.0-0 <0.18.0-0 @jupyterlab/notebook
>=0.15.5-0 <0.16.0-0   >=0.17.0-0 <0.18.0-0 @jupyterlab/apputils

**Comment by vidartf** [comment]
Yeah, given the beta nature of Jupyter Lab (from the perspective of extension devs), there's not much focus on supporting older versions.
