### ISSUE TITLE
open nbdiff-web from the jupyter tree

### ISSUE THREAD

**Issue by laurentperrinet** [jupyter/nbdime#431]
I love ``nbdime`` and use it extensively - thanks for this tool! 

I have sometimes clutter in my workflow (sometimes by having conflict files) - I usually clean that by copy-and-pasting file names in the terminal

It would be a great enhancement to be possible to do that directly from the jupyter tree, as in this screenshot:

![image](https://user-images.githubusercontent.com/381808/47014607-01ef1c00-d14b-11e8-9605-a64bfd148e64.png)

in addition  to "duplicate", "edit", ... a "nbdiff" button (as in the jupyter extension) would be great.

**Comment by vidartf** [comment]
So, you mean a button that is only enabled if you select two notebooks? That sounds reasonable.

If you want to have a go at it, the [nbextension code](https://github.com/jupyter/nbdime/blob/master/nbdime/notebook_ext/index.js) in itself is not that large. Needed steps:
1. Add a button.
2. When clicked, get the paths of the selected notebooks and pass them to [`nbDiffView`](https://github.com/jupyter/nbdime/blob/20e07f464789c8d6099de4d94383a63f71907190/nbdime/notebook_ext/index.js#L23).
3. Listen to changes in the file selection.
4. Only enable the button when two *notebooks* are selected.

**Comment by vidartf** [comment]
Actually, you could (should?) make a separate script file to be registered as a tree extension. Use:

```
jupyter nbextension enable --section=tree <other args>
```

**Comment by laurentperrinet** [comment]
I have looked at this possibility and I am not enough of an expert in JS to get around it 

:-/

maybe the idea will hop around and find somebody with the right knowledge :-)
