### ISSUE TITLE
Documentation bug - console commands for nbmerge

### ISSUE THREAD

**Issue by obarak** [jupyter/nbdime#432]
The command-line documentation for `nbmerge` says that `-o/--output` is used to choose the output file, when in fact the right switch is `--out` (appears correctly when doing `nbmerge -h`).

The wrong switch appears both [here](https://nbdime.readthedocs.io/en/stable/cli.html#nbmerge) and [here](https://nbdime.readthedocs.io/en/stable/cli.html#nbmerge-web) (`-o` is used in the example command) .

Thanks!

**Comment by vidartf** [comment]
Thanks! This is an issue of the documentation being outdated.

**Comment by vidartf** [comment]
Note: For now I've set the docs to point to "latest" (built from master), so that this will be included. We should switch back to "stable" after next release.
