### ISSUE TITLE
Force nbdime to use git from conda

### ISSUE THREAD

**Issue by marhoy** [jupyter/nbdime#434]
I have cluster of CentOS 7 machines, where the system-installed git is too old for nbdime (1.8.3.1).
I have installed the git conda-package, so I also have a newer git inside the conda-environment.

But nbdime still uses the system-installed git, probably because the conda-version is at the end of os.environ['PATH'].

How can I force nbdime to use the git binary in the conda-environment?

**Comment by vidartf** [comment]
There should hopefully not be anything nbdime specific here, but just for reference, the call that fails in nbdime is in the git filter integration right?

What does `which git` give at the terminal (with the env activated)?
What does `python -c "import shutil; print( shutil.which('git') )"` give?

**Comment by marhoy** [comment]
Confusingly, that gives (after activating the environment):
```
$ python -c "import shutil; print( shutil.which('git') )"
/home/applications/miniconda/envs/python3/bin/git
```

But inside a cell in a Jpuyter Notebook, I get:

![image](https://user-images.githubusercontent.com/22790786/47152572-5aeeb980-d2dd-11e8-86c9-7cbf62ebc043.png)

**Comment by vidartf** [comment]
What happens in the notebook should not matter for nbdime, but FYI: The kernel is likely not running in your env. There is a way to set things up so that all your conda envs get listed as a separate kernel.

Could you let me know the output of these commands:
```bash
python -c "from subprocess import check_output; print( check_output(['git', '--version']) )"


python -c "from subprocess import check_output; print( check_output(['git', '--version'], shell=True) )"

**Comment by vidartf** [comment]
Also, it might be relevant to know how nbdime gets called. Are you calling it with `nbdiff ...` or is it being called via `git diff ...` ?

**Comment by marhoy** [comment]
I have tried to install the conda-package nb_conda_kernels, but that did not solve the problem.

Regarding git-version from subprocess, I get this with shell=False:
```
$ python -c "from subprocess import check_output; print( check_output(['git', '--version']) )"
b'git version 2.17.1\n'
```

and this with shell=True:
```
$ python -c "from subprocess import check_output; print( check_output('git --version', shell=True) )"
b'git version 2.17.1\n'
```

So both om them executes the correct git-binary from the conda enviroment.

I run nbdime via an nbextension that adds a button to the top of the Notebook:

![image](https://user-images.githubusercontent.com/22790786/47204827-8ed0ea00-d384-11e8-9fc7-ba71e39e044d.png)

If I run "nbdiff notebook.ipynb" in a shell (with the environment activated), it works as expected.

**Comment by vidartf** [comment]
What is the error message you are getting?

**Comment by vidartf** [comment]
Other info:
- How do you start your notebook?
- Where is nbdime installed? Which environment?

**Comment by vidartf** [comment]
Thanks for the detailed debrief!
