### ISSUE TITLE
No pager in git bash on windows?

### ISSUE THREAD

**Issue by babrodtk** [jupyter/nbdime#435]
Great work with this tool - love it so far!

Working with git from the git bash on Windows it works very well for a single file, but it does not show the diff in a pager like git usually does (e.g., using less / more). Is this something that is possible to support or am I doing something wrong with my setup?

**Comment by vidartf** [comment]
I'm not sure what triggers git to use a pager or not, but I assume it simply does not know exactly what the external diff application will do (maybe it opens a UI?), and therefore does not page the output. I'm not sure if it makes sense for nbdime to page its own output, e.g. as it would be on a per-file basis.

As a workaround, you should be able to pass git references to `nbdiff`, which you can then pipe to more/less yourself. Can you think of any better ways to do it?

**Comment by vidartf** [comment]
Closing as resolved. As far as I can see, there are two decent options:
- Configure your gitconfig manually to pipe the output of nbdime via your pager of choice (e.g. less/more).
- Use `nbdiff` and pipe its output to the pager of your choice.
