### ISSUE TITLE
Merge/diff postional arguments

### ISSUE THREAD

**Issue by noklam** [jupyter/nbdime#436]
The current nbmerge only accept merging 3 notebooks --> base local and remote, where sometimes what I really want it merging two local copies, especially when I want to use the web merge-tool. 

Also for the nbdiff, in the -h information it said base remote but I can compare two local files which feels a bit confusing. I am not sure is it getting the local or remote version.

`When I do nbdiff a.ipynb b.ipynb` where it does not have any git history inside the folder, it looks like it simply compare two file, what if there is a remote branch exist but I only want to compare the two file in local repository?

nbmerge
```
Merge two Jupyter notebooks "local" and "remote" with a common ancestor
"base".

positional arguments:
  base                  The base notebook filename.
  local                 The local modified notebook filename.
  remote                The remote modified notebook filename.


```
nbdiff
```
usage: nbdiff [-h] [--version] [--config]
              [--log-level {DEBUG,INFO,WARN,ERROR,CRITICAL}] [-s] [-o] [-a]
              [-m] [-d] [--color-words] [--no-color] [--no-git]
              [--no-use-diff] [--out OUT]
              [base] [remote] [paths [paths ...]]

Compute the difference between two Jupyter notebooks.

positional arguments:
  base                  the base notebook filename OR base git-revision.
  remote                the remote modified notebook filename OR remote git-
                        revision.
  paths                 filter diffs for git-revisions based on path
```

**Comment by vidartf** [comment]
> The current nbmerge only accept merging 3 notebooks --> base local and remote, where sometimes what I really want it merging two local copies, especially when I want to use the web merge-tool.

The base notebook is normally considered important meta information. If you use an empty notebook as the base, do you get the behavior you want? If so, maybe having base default to an empty notebook makes sense (any common changes are agreed and not conflicted).

For `nbdiff`, when the command is given two notebooks as arguments, it will simply compare those two files. Otherwise, it mimics the signature of `git diff`. This should probably be made clearer in the help text.

**Comment by noklam** [comment]
@vidartf  Thanks, I think an empty base notebook works for this use case.

Thanks, a better help text will definitely help. Two follow up questions about merge. Firstly, does nbmerge-web the same as nbdime mergetools? I am a bit confusing on these two tools, there is very little doc about these 2 function. 

Secondly, when I do nbmerge base local remote, are the notebooks are required to sit inside my local folder already? In the help text it said OR remote git-revision, but I do not know how to do so. I was expecting I should do nbmerge a.ipynb a.ipynb a.ipynb while it compare the same notebook from my git history instead of have 3 copies of notebook extracted from the repo.
```
positional arguments:
  base                  the base notebook filename OR base git-revision.
  remote                the remote modified notebook filename OR remote git-
                        revision.
  paths                 filter diffs for git-revisions based on path
```

**Comment by vidartf** [comment]
> Firstly, does nbmerge-web the same as nbdime mergetools?

`nbdime mergetools` is intended as an alias for `git mergetool --tool nbdime -- *.ipynb`. As such, it is mainly an ease of access command.

> Secondly, when I do nbmerge base local remote, are the notebooks are required to sit inside my local folder already? In the help text, it said OR remote git-revision, but I do not know how to do so. In the help text, it said OR remote git-revision, but I do not know how to do so. 

`nbmerge` does not support git revisions, only `nbdiff` does. You might be mixing up the two commands? I'm not really sure what you are asking here. If you could list 1) what do you want to do 2) how would you intuitively expect to achieve this with nbdime, then I could maybe better understand.

**Comment by noklam** [comment]
Thanks, now I get what nbdime mergetool is.
I am sorry I mix up the help text for nbdiff and nbmerge, the main confusion was about the git-revision. So nbmerge only works with files.

**Comment by vidartf** [comment]
> So nbmerge only works with files.

Yes. The only reason git revisions are supported in nbdiff is to work around a problem with git. Normally any integration with the VCS should be initiated from the VCS in question (git or mercurial). For merging, this works as intended.

**Comment by vidartf** [comment]
Looking at using an empty notebook with nbmerge now, I realized there is an existing workaround: you can supply `/dev/null` / `nul` as the base file argument (use `nul` on Windows, otherwise `/dev/null`). I'm implementing this as the default value of base now, but at least you can use this workaround immediately.
