### ISSUE TITLE
Question: where is nbdime executable

### ISSUE THREAD

**Issue by javadba** [jupyter/nbdime#442]
The docs say 

  > nbdime config-git --enable --global

But there is no `nbdime` in the repo or after running `pip install`.    Thoughts?

**Comment by vidartf** [comment]
Nbdime uses Python entry points. As such, the nbdime executable/script will be managed by Python, and will typically reside in a folder in the Python install. Typically, you can find the location of nbdime by the terminal command `which nbdime` or `where nbdime` (depending on your platform). If you cannot find nbdime, it might be that the necessary folders from Python are not on the path. You might also launch the `nbdime` command with `python -m nbdime`.

**Comment by javadba** [comment]
I use python installed from brew - for which the executables are in `/usr/local/Cellar/python3/3.6.4_4/bin` (and is on the $PATH). But in any case an exhaustive search  `find /usr -name nbdime` had been attempted before posting.  I'll do same but from `/` now ..

**Comment by vidartf** [comment]
I don't have any experience with the excepted paths for OSX, but yes, I would expect the `/bin` folder to be on the path.

**Comment by javadba** [comment]
I manually added to my path:

  export PATH=/usr/local/Cellar/python3/3.6.4_4/bin:/Users/sboesch/Library/Python/3.6/bin:$PATH

now nbdime does show up.  However I am unable to add extensions:  

nbdime extensions --enable

  File "/usr/local/Cellar/jupyter/1.0.0_1/libexec/vendor/lib/python2.7/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
ImportError: No module named nbdime

**Comment by lucasdurand** [comment]
Looks like it's looking in the wrong pythonpath. Things can get a bit tricky when you have both Python 2 and 3 installed. 

Check what your PYTHONPATH is and make sure it's pointing to the python3 install.

**Comment by javadba** [comment]
PYTHONPATH is empty - and one or more tools requires it to be that way
iirc.  Would that be an issue here?

Am Do., 22. Nov. 2018 um 10:56 Uhr schrieb Lucas Durand <
notifications@github.com>:

**Comment by lucasdurand** [comment]
I'm guessing that `which nbdime` is going to be pointing into your python 2 install? See if you installed it for python 2 as well. Might need a pip uninstall nbdime to get rid of it.

**Comment by javadba** [comment]
$which nbdime
/Users/sboesch/Library/Python/3.6/bin/nbdime

**Comment by javadba** [comment]
nbdime extensions --enable --debug

This was a _tough_ installation.  Maybe add to the documentation

*Make sure to upgrade jupyterlab to latest version first*

I had done a bunch of spelunking before discovering that as the latest issue.

**Comment by javadba** [comment]
How do we compare two arbitrary git commits?   The following is working! but it is not seemingly configurable? It is hard-coded to compare the local version to HEAD?

![image](https://user-images.githubusercontent.com/410769/48923724-deb03e80-ee65-11e8-882b-7ff118a0a8be.png)

I want to do a code review - so comparing to local is not the goal. Instead we can manually enter the git commit version from the PR. We need a way to specify the pari of git commits to use in the comparison. Is there any way to do this  - including if need be via the command line?

**Comment by javadba** [comment]
Looks like we are supposed to use `git diff` .. ?

```
$git diff  cffc28a0f13a6e473cda9e7ef7d4f57864c7626f HEAD -- src/nb/BlockMatch.ipynb
[E __init__:80] Notebook JSON is invalid: 'execution_count' is a required property

Failed validating 'required' in execute_result:

On instance['cells'][1]['outputs'][0]:
{'data': {'text/html': '<style>.container { width:100% !important; }</style>',
          'text/plain': '<IPython.core.display.HTML object>'},
 'metadata': {},
 'output_type': 'execute_result'}

```

It *appears* that the command worked.. But are we then limited to _command line_ diffs .. ?  I'd really like a gui version of this diff.  Will look a bit more.

**Comment by javadba** [comment]
I'm going to *close* this thread. Thx for the responsiveness.
