### ISSUE TITLE
ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by stephanecollot** [jupyter/nbdime#443]
Hello

I have this error
```
 $ nbdiff
...
miniconda2/lib/python2.7/site-packages/nbdime/gitfiles.py", line 110, in _get_diff_entry_stream
    ret = apply_possible_filter(path)
miniconda2/lib/python2.7/site-packages/nbdime/vcs/git/filter_integration.py", line 64, in apply_possible_filter
    filter_attr = interrogate_filter(git_path)
miniconda2/lib/python2.7/site-packages/nbdime/vcs/git/filter_integration.py", line 24, in interrogate_filter
    path_list, attr, info = [s.decode('utf8', 'replace') for s in spec.split(b'\x00')[:3]]
ValueError: need more than 1 value to unpack
```

With Python 2.7 and nbdime 1.0.3

Cheers

**Comment by vidartf** [comment]
Hello, and thanks for your report. I think this is a duplicate of #417. That seemed to have slipped a bit between the cracks, so I will try to get that released shortly. I will comment again after I do the release, so you can confirm whether the fix works for you!

**Comment by vidartf** [comment]
Ok, i just pushed 1.0.4 to PyPI. It might take some time to propagate, but when possible, I'd appreciate if you could test whether it fixes your issue!

**Comment by stephanecollot** [comment]
Awesome it is working!
Thanks
