### ISSUE TITLE
nbdime made long input cells scrollable

### ISSUE THREAD

**Issue by hojo0590** [jupyter/nbdime#445]
I hope im correct here and I have not overseen an exsisting issue taking on the same problem but the installation of nbdime made some really long input cells (54 lines+) scrollable in jupyter lab.
Same happened to a co-worker.
For us 'only' uninstalling nbdime solved the problem.
Most interesting thing that I can't really explain is, that this problem showed in different environments (in which nbdime was not installed). Rebuilding jupyter lab with nbdime installed did not help. Only uninstalling it - after jupyter's extension rebuild everything went back to normal.

**Comment by vidartf** [comment]
Thanks for your report! This seems to be a CSS issue.

An initial investigation of the source points to this rule: https://github.com/jupyter/nbdime/blob/d71758d69faa57257e5d6cc97da6a02f54b53160/packages/nbdime/src/styles/common.css#L19-L21

This rule should either:
- be scoped in a narrower fashion
- moved to the 'webapp' package styles, as it might not be useful or a lab extension at all

My best bet is on the second alternative, but we just have to check that nothing else breaks, and of course that this is enough to fix the problem in full.

As a heads-up, I'm not going to be able to work on this for a few weeks. If you or anyone else wants to have a go at making the needed changes in the meanwhile, please go ahead!

**Comment by vidartf** [comment]
Fix proposed in #462.
