### ISSUE TITLE
"422 Unprocessable Entity" when calling from notebooks

### ISSUE THREAD

**Issue by kalenkovich** [jupyter/nbdime#447]
The nbdiff starts but only the following is shown:

```
Notebook Diff
Hide unchanged cells  Trust outputs
Base                                                  Remote
422 Unprocessable Entity
```

Running nbdiff-web from CLI works normally.

**Comment by vidartf** [comment]
Hi, and thanks for the report! This error is often seen when it cannot find one of the files in question. Often, there is more debug output in the notebook server terminal. Do you see any such output, and if so, could you share it? Also, which version of nbdime are you using?

**Comment by kalenkovich** [comment]
Hi, @vidartf. Thank you for your reply.

Embarrassingly (and also luckily) the issue went away without me doing anything on purpose. If I encounter it again I'll make sure to provide the information you suggested.

Sorry for posting a non-issue.
