### ISSUE TITLE
Swagger Spec for Server API

### ISSUE THREAD

**Issue by jaipreet-s** [jupyter/nbdime#449]
This issue is a request for a swagger spec for the REST API to enable building different frontends for the diff/merge view.

**Comment by vidartf** [comment]
Hi Jaipreet!

I don't have any experience with swagger specs, but if you'd like to give it a go, I can try to answer questions about the API as well as I can.

Should I see this issue in relation to https://github.com/jupyterlab/jupyterlab-git/pull/200 ? As that PR has been stonewalled, I'm curious what your plans are.

**Comment by jaipreet-s** [comment]
Thanks Vidar, I'll try and have a stab at this.

Yes, This is loosely related to https://github.com/jupyterlab/jupyterlab-git/pull/200. Sincere apologies for the delay on the PR.  If you could add some context on the PR on how the `IGitExtension` would be used, I can merge it in and we can iterate from there.

**Comment by vidartf** [comment]
Closing as stale. Feel free to comment further if there is anything more here.
