### ISSUE TITLE
diff web tool not launching

### ISSUE THREAD

**Issue by ggrrll** [jupyter/nbdime#451]
Hi,

first of all thanks for the nice tool.

I am triyng to launch the web UI with

`git difftool -g <commit_id my_notebook.ipynb` 

but it still gives me the diff inside the console... 

I have this in my `.gitconfig`

```
[diff "jupyternotebook"]
        command = git-nbdiffdriver diff
[merge "jupyternotebook"]
        driver = git-nbmergedriver merge %O %A %B %L %P
        name = jupyter notebook merge driver
[difftool "nbdime"]
        cmd = git-nbdifftool diff \"$LOCAL\" \"$REMOTE\"
[difftool "nbdime"]
        cmd = git-nbdifftool "$LOCAL" "$REMOTE"
[difftool]
        prompt = false
[mergetool "nbdime"]
        cmd = git-nbmergetool merge \"$BASE\" \"$LOCAL\" \"$REMOTE\" \"$MERGED\"
[mergetool]
        prompt = false
```

Thanks for your support

ps: on mac os 10.14.1 and safari 12

**Comment by vidartf** [comment]
Hi,

There are some issues with using external diff tools via git. To work around this problem, `nbdiff-web` was changed to accept similar arguments to git diff/difftool:
```
nbdiff-web [<commit> [<commit>]] [<path>]
```
It is not ideal, but given the behavior of git, it is the best alternative. Hopefully this works ok for you.

**Comment by ggrrll** [comment]
ah, great, thanks! @vidartf --  didn't realise that was an option too 

-- you can close it, if you want

**Comment by vidartf** [comment]
If you (or anybody else) have any suggestions for ways of improvement (e.g. documentation), feel free to suggest that here. I'll close the issue in the meantime, but will reopen if anything useful is suggested!
