### ISSUE TITLE
403: Forbidden Error

### ISSUE THREAD

**Issue by maxfrei750** [jupyter/nbdime#455]
Hello!

I'd like to reach the nbdiff-web interface over my LAN. Therefore, I tried to start it with:
`nbdiff-web --ip 192.168.0.13 -p 9999`

However, when I try to access it over LAN, I get the following error:

> Blocking request with non-local 'Host' 192.168.0.13 (192.168.0.13:9999). If the notebook should be accessible at that name, set NotebookApp.allow_remote_access to disable the check.

I already tried to set `c.NotebookApp.allow_remote_access=True` in the jupyter_notebook_config.py, but that did not work (which did not really suprise me). However, I dont know where else I should put it, because there does not seem to be an equivalent file for nbdime. So how do I have to set up nbdime, in order to reach it over LAN?

Kind regards and thanks in advance!

**Comment by lc0** [comment]
same problem on my side @maxfrei750

**Comment by minrk** [comment]
This should be fixed by #457

**Comment by lc0** [comment]
thank you @minrk. I almost already found a super hacky solution to solve this. This solution is way better! 

Looking forward to this getting merged

**Comment by maxfrei750** [comment]
@minrk Nice! Thank you very much! Hope this is going to be merged soon.
