### ISSUE TITLE
Add http|https options for external assets in nbdiff-web

### ISSUE THREAD

**Issue by ned2** [jupyter/nbdime#459]
I'm trying to run nbdiff on AWS Sagemaker (using Jupyter Lab) but running into the problem that the Jupyer Lab instance is being hosted with https, whereas the CDN URI for Font Awesome is hardcoded with an http URI, which results in that a failed web request due to mixed content.

Perhaps a parameter to specify whether http or https should be used could help here?

**Comment by vidartf** [comment]
Is there a reason to not always use https? If not, we can just add the 's' to the hardcoded URL. All the scripts for the webapp pages are loaded via hardcoded https URLs (promise polyfill and requirejs).

**Comment by ned2** [comment]
If that won't result in the same mixed connect error in the reverse
direction, then I guess not. I must admit to not knowing enough to answer
that either way.

**Comment by vidartf** [comment]
Mixed content should only be one way, ref first paragraph [here](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content):

> Mixed content occurs when initial HTML is loaded over a secure HTTPS connection, but other resources (such as images, videos, stylesheets, scripts) are loaded over an insecure HTTP connection. This is called mixed content because both HTTP and HTTPS content are being loaded to display the same page, and the initial request was secure over HTTPS.

**Comment by ned2** [comment]
Ah, right, cool. Then yeah, I don't see any reason why not just using https
for those CDN assets.

**Comment by vidartf** [comment]
Fixed, will be released after the current spate of fixes have been dealt with.
