### ISSUE TITLE
nbdiff never finishes

### ISSUE THREAD

**Issue by bollwyvl** [jupyter/nbdime#46]
Hi folks! Been tracking the work. Looking good!

I have found a pair of reasonably large notebooks (1.7mb each) for which `nbdiff` doesn't finish. I've left it running overnight!

```shell
!curl -L https://notebooks.anaconda.org/anaconda-cluster/notebook-blaze-impala/download?version=1.0 > before.ipynb
!curl -L https://notebooks.anaconda.org/stephenakearns/notebook-blaze-impala-copy1/download?version=2016.04.29.0856 > after.ipynb
!du -h *.ipynb
!nbdiff before.ipynb after.ipynb
```

Any thoughts? I haven't dug enough into the implementation, but would do so if need be!

**Comment by vidartf** [comment]
@bollwyvl Thanks for pointing this out. It seems to be an issue with how it's handling diffs of long strings (using difflib). In the example files you posted these longer strings are equal, which can (and should) be short circuited, but the issue will still be valid for longer, non-equal strings. I'll be looking further into this, but thought I'd share these initial findings.

**Comment by bollwyvl** [comment]
Great! Thanks for looking into it! Let me know if I can be of further
assistance... I don't know of a higher-performance drop-in replacement for
difflib, but maybe we can do _something_? optional numba jitting?

**Comment by vidartf** [comment]
The current implementation does character-based diffs on strings, which scales as ~square of string length. The most common (best practice?) solution is to split such strings into logical parts (typically by line endings, see #17). However, this does not readily apply for embedded data, minified javascript or other such formats.

As far as I know, the current plan is to handle (certain) mime types better, e.g. HTML such that different parts of the output can be handled intelligently (embedded css/js/data/images).

**Comment by martinal** [comment]
Difflib is only used for strings, the sequence diff for lists (including cell lists) is a brute force O(N^2) algorithm that should be replaced with another one such as the Myers diff algorithm. I started implementing that but had some bugs and postponed debugging that until other issues were resolved. The implementation is in test_myers or something.

**Comment by vidartf** [comment]
@bollwyvl The code in #47 should handle these files by splitting on lines. One of the js lines there is still ~400k chars wide, but that is at least manageable in reasonable time.

**Comment by bollwyvl** [comment]
Ah, thanks for the Myers hint. Here's a python wrapper around a c++ implementation of Google's diff_match_patch:

https://github.com/JoshData/diff_match_patch-python

Limitations:
- Only works on strings
- would need Yet Another Diff Format Convertor

Has rather impressive performance:

```python
from diff_match_patch import diff

from nbdime.diffing.sequences import (
    diff_sequence_bruteforce,
    diff_sequence_difflib,
)

%%time
results.append(diff_sequence_bruteforce(before, after))
CPU times: user 1min 6s, sys: 980 ms, total: 1min 7s
Wall time: 1min 8s

%%time
results.append(diff_sequence_difflib(before, after))
CPU times: user 2.63 s, sys: 5.72 ms, total: 2.64 s
Wall time: 2.64 s

%%time
results.append(diff(before, after))
CPU times: user 689 ms, sys: 28.1 ms, total: 717 ms
Wall time: 716 ms
```

**Comment by vidartf** [comment]
Ref #3.

**Comment by vidartf** [comment]
Fixed in master
