### ISSUE TITLE
custom config of git nbdiff button

### ISSUE THREAD

**Issue by ggrrll** [jupyter/nbdime#461]
Hi, 

thanks for the nice extension.

Is it possible to configure the `git nbdiff` button in the notebook toolbar  to include the `nbdiff-web` options (especially for the `ignorables` ) ?

Do we have to change the `.gitconfig` ?

Thanks

**Comment by vidartf** [comment]
Hi,

Thanks for the kind words. To configure the extension view, use the `Extension` key in the [config](https://nbdime.readthedocs.io/en/latest/config.html).

Which ignorables do you want to configure? If you just want to use the standard categories of source/metadata/outputs/details, you can configure it e.g. with a config file like this:
```json
{
  "Extension": {
    "details": false
  }
}
```

If you want more fine-grained control, see [this subsection](https://nbdime.readthedocs.io/en/latest/config.html#configuring-ignores) of the docs.

Let me know if there are any problems, or if you have any suggestions for the docs :)

**Comment by ggrrll** [comment]
@vidartf  thanks for pointing to the docs. 

However, it's not clear how to make those changes to the `nbdime_config.json` file  (sorry, not a terminal expert) -- maybe you could add an example? :)
  -- I couldn't find that file to edit it  in the `config` paths of `jupyter --paths` 

```
/Users/lazzari/.jupyter
/Library/Frameworks/Python.framework/Versions/3.6/etc/
/usr/local/etc/
/etc/jupyter
```
...is there a CL solution ?

Thanks!

**Comment by vidartf** [comment]
@ggrrll No worries. Let's first get you up and running. Then afterwards, let's see try to write such an example based on this.

The way to set up the config file is to create a file `nbdime_config.json` in one of those directories you listed. E.g. to create the file `/Users/lazzari/.jupyter/nbdime_config.json`. You can do this any way you want (from an editor, via the OS file-browser, or via a terminal). There is currently no nbdime CLI for this.

**Comment by ggrrll** [comment]
Hi,

thanks -- yeah, I think it should be made clear that one has to create that file...

anyways, this is what  I have now in my configs:

```
{
    "NbDiffWeb": {
        "Ignore": {
            "/cells/*/metadata": true
        }
      },
    "NbDiff": {
        "Ignore": {
            "/cells/*/metadata": true
        }
      },
    "NbDiffTool": {
        "Ignore": {
            "/cells/*/metadata": true
        }
      }      
  }
```

but it's not working yet...

recap on wanted behaviour: by clicking the `git nbdiff` button, I would like the same output of 
`nbdiff-web -M my_notebook`

Thanks!

**Comment by vidartf** [comment]
To replicate the `-M` option, you can use this config:
```json
{
  "Diff": {
    "metadata": false
  } 
}
```

**Comment by vidartf** [comment]
For reference, what you wrote is correct, but should also include the `Extension` key:
```json
{
  "Extension": {
    "Ignore": {
      "/cells/*/metadata": true
    }
  }
}
```

**Comment by ggrrll** [comment]
> To replicate the `-M` option, you can use this config:
> 
> ```json
> {
>   "Diff": {
>     "metadata": false
>   } 
> }
> ```

Thanks! this is indeed working now :)

**Comment by vidartf** [comment]
Good to hear. If you want to write up an example that would've made sense to you for the docs, you can do that directly from github by editing this file: https://github.com/jupyter/nbdime/blob/master/docs/source/config.rst No pressure though (ok, a tiny bit maybe 😄).
