### ISSUE TITLE
dockerfile for building this from source

### ISSUE THREAD

**Issue by Godley** [jupyter/nbdime#464]
Hi there,

Just figured I'd let you know in our fork we have a working Dockerfile for building this from source: https://github.com/dotmesh-io/nbdime/blob/master/Dockerfile 

needed this rather than doing `pip install nbdime` because we had some other changes we made in order to integrate it into the product we're building. We also ripped out some features (uploading a file object over the api, accessing files from local storage, limiting the scope of urls) in order to make it secure when running in a container on a web server.

The Dockerfile looks a bit complicated because we found just doing `pip install .` inside a container meant the `lerna bootstrap --hoist` command failed for unknown reasons.

Let me know if there's anything you want us to submit as a PR upstream (I just submitted a bug I found while doing this using my own fork), and thank you for making this project so that we didn't have to build notebook diffing ourselves.

**Comment by vidartf** [comment]
Hi, and thanks for sharing!

I'm happy this is useful, and I'm glad to see that most of your changes so far are specific to the webapp. Hopefully, most the changes you have made outside of webapp can be contributed back (are there anything there is not currently an issue for that could benefit from being here?).

I'm not sure what your future plans are, but if you see that all the changes you need can be realized within the webapp components, it might be easier to mainten by using nbdime as a library dependency. But I can see that it might make sense to start it out as a fork.

Regarding the lerna issue, you can generally get more detailed logs with `pip install -v .`. My prime suspect for now is that you locked the inter-repo dependencies:
```diff
package.json:
- "nbdime": "^4.0.0"
+ "nbdime": "4.0.0"
```

That might throw lerna off, as it tries to match that to whatever is in `./packages/nbdime`.

**Comment by Godley** [comment]
I haven't seen any so far but I will keep an eye out. As you say, the majority of changes are to the webapp.

That's a good point actually, I suppose, if the format given back by the library is interoperable it might be easier to just depend on it as a library. We'd probably still need the python api though as the rest of our codebase is in golang.

Ah I actually tried to fix the lerna issue using that - that's caused some problems in the past and strikes me as risky if there's new releases or npm happens to cache different versions on different machines (for external dependencies at least). Also doing the install separately (npm first, then a build, then a pip install) means we cache as much as possible - pip doesn't seem to be very good at that.

The -v tip is useful though, I shall have a look into that :)

**Comment by vidartf** [comment]
Note: If you want to keep the package versions locked in the package.json, then I think the inter-repo dependencies should always match. E.g. `"nbdime": "4.0.0"` should be `"nbdime": "4.0.1"`, since that is the current version in `./packages/nbdime/package.json`. Since lerna links these packages, it shouldn't pull it from the registry.

**Comment by vidartf** [comment]
Closing this as a reference.
