### ISSUE TITLE
Using CellDiffWidget -  layout issue

### ISSUE THREAD

**Issue by jaipreet-s** [jupyter/nbdime#486]
Hi @vidartf and others,

I’m attempting to use the CellDiffWidget inside the Git extension and am running into a layout issue. 
When I plainly use new CellDiffWidget, layout of the line number, source code, and the line number background is off [1]. 
From what I can tell, this is mostly affected by these two styles. When I manually add these using developer tools, it looks better

```
.CodeMirror-gutter.CodeMirror-linenumbers {
  width: 29px;
}

.CodeMirror-sizer {
  margin-left: 47px;
}
```
I’m not sure where these inline styles are being added on these CodeMirror DOM elements. Hoping you have some pointers around how to effectively layout this widget. LMK if you need more info. Thanks!

[1]
![nbdime-gitext](https://user-images.githubusercontent.com/43826141/60774409-882c0380-a0c8-11e9-8173-657703de2617.png)

[2] NBDime Lab Extension
![nbdime-labext](https://user-images.githubusercontent.com/43826141/60774417-95e18900-a0c8-11e9-8efc-3dc5eb2021a4.png)

**Comment by jaipreet-s** [comment]
FWIW I was able to get this lay-outing somewhat cleanly by adding

```
.CodeMirror-gutter.CodeMirror-linenumbers[style] {
  width: 29px !important;
}

.CodeMirror-sizer[style] {
  margin-left: 47px !important;
}
```

**Comment by vidartf** [comment]
There might be some styles from a dependency that you are missing. Try adding all of these to see if it gets fixed. If they do, you can go through them in detail and figure out which ones you need:

https://github.com/jupyter/nbdime/blob/0590d1b1318766d3aadc58932a3795b0a6fc5f1a/packages/labextension/src/index.ts#L6-L14

**Comment by jaipreet-s** [comment]
Thanks. I'm going to resolve this as I found a work around.
