### ISSUE TITLE
nbdime extension not supported in the lastest version of jupyterlab v 

### ISSUE THREAD

**Issue by persas** [jupyter/nbdime#487]
When trying to install the nbdime extension on the lastest version of jupyterlab I get the following error:

![image](https://user-images.githubusercontent.com/23346350/61130904-15e86400-a4b8-11e9-8e50-154ff1961871.png)

**Comment by bavaria95** [comment]
Extension hasn't yet been updated to 1.0 of JupyterLab. There's an ongoing pull request:
https://github.com/jupyter/nbdime/pull/483

**Comment by vidartf** [comment]
Closed in #483.
