### ISSUE TITLE
embedding merge tool in another tornado application?

### ISSUE THREAD

**Issue by hhuuggoo** [jupyter/nbdime#490]
I'm looking into embedding the merge web UI into another tornado application.  I'm importing `MainMergeHandler` and `ApiMergeHandler`, copying over templates and `nbdime.js`.

However, when I render the page, it seems like the layout code isn't behaving properly?

with nbdime, I get the following:

![Screenshot from 2019-07-29 11-22-15](https://user-images.githubusercontent.com/249407/62060515-425bea00-b1f3-11e9-8015-5485b35fd8a0.png)

But with my application, I get:

![Screenshot from 2019-07-29 11-22-34](https://user-images.githubusercontent.com/249407/62060525-4b4cbb80-b1f3-11e9-97a6-d21683b39924.png)

The height of the cell is way too large in my application, and in the javascript console, I'm getting warnings about requestAnimationFrame

![Screenshot from 2019-07-29 11-24-08](https://user-images.githubusercontent.com/249407/62060587-67e8f380-b1f3-11e9-871b-d2d01487fb53.png)

Any ideas?  Thanks

**Comment by vidartf** [comment]
A little hard to troubleshoot without having more details, but I think all the files in `packages/webapp/static` (after a build) would need to be copied over, not just `nbdime.js`. Without all the files, you can miss both critical JS, as well as CSS.

**Comment by hhuuggoo** [comment]
Somehow I made an error translating the nbdime tornado template to my own template - still not sure what I did wrong but when I copy nbdime's template, everything is good, so something must have gotten dropped.

Thanks!
