### ISSUE TITLE
Buttons not aligned in JupyterLab

### ISSUE THREAD

**Issue by jasonyan0302** [jupyter/nbdime#493]
<img width="397" alt="Screen Shot 2019-08-07 at 8 59 34 PM" src="https://user-images.githubusercontent.com/11763226/62674301-acdcfa80-b956-11e9-928a-6b6ddb68c843.png">
When installed in JupyterLab, the 2 buttons are not aligned with the other buttons in the action bar.

**Comment by vidartf** [comment]
Thanks for the report! I thought I had fixed that, but it seems not. I'll have to search around my local repo to see if I have the fix laying around somewhere.

**Comment by vidartf** [comment]
I think this is only an issue with older version of JupyterLab (<1.0), if so, it will not be fixed. If you are still seeing this lab > 1.0, please share the version number of jupyterlab, nbdime, and the nbdime labextension (`jupyter labextension list`).

**Comment by jasonyan0302** [comment]
Switched to a newer version and it's fixed. Thanks! :)
