### ISSUE TITLE
Extension controls - enabling / disabling toolbar buttons

### ISSUE THREAD

**Issue by psychemedia** [jupyter/nbdime#499]
By default, the installed notebook extension provides two buttons for launching `nbdime`:

- a diff-er against a checkpointed version of the notebook;
- a diff-er against a git committed version of the notebook.

It would be useful if the extension provided nbextensions UI controls that allow the display of these buttons to be individually selected or disabled.

**Comment by vidartf** [comment]
> It would be useful if the extension provided nbextensions UI controls that allow the display of these buttons to be individually selected or disabled.

I don't really understand what you are saying here (maybe due to my lack of experience writing nbextensions). Would you mind expanding on this?

**Comment by psychemedia** [comment]
Sure, sorry for not being clearer.

The Jupyter notebook [extensions configurator](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator) can display a control panel for an extension when provided with an appropriately defined YAML file.

It would be handy if the `nbdime` extension provided a configurator display with a couple of checkbox options:

- enable checkpointed file diff button;
- enable last git commit diff button.

Then the user could install the extension and decide whether to enable the display of one, both, or neither toolbar buttons.

My use case is I want to provide the extension to students so they can diff solely against checkpointed notebooks. They are not working in a git environment and the git-diff button is superfluous.

**Comment by vidartf** [comment]
You seem to have decent control of the technology involved. Would you mind doing a PR? The nbextension code is pretty self-contained: https://github.com/jupyter/nbdime/blob/master/nbdime/notebook_ext/index.js

**Comment by vidartf** [comment]
Note the existing code for checking whether or not to add the git button (it will not add the git button if the notebook is not contained within a git repository).
