### ISSUE TITLE
git show and git diff

### ISSUE THREAD

**Issue by tienduccao** [jupyter/nbdime#510]
Hi, I'd like to know how to have the same output when executing `git show` and `git diff`.

For `git diff`, I configured `~/.gitconfig` as below
```
[diff "jupyternotebook"]
    command = git-nbdiffdriver diff --ignore-metadata --ignore-outputs --ignore-details
```
Currently the `git show` command returns the diff of the notebook's JSON format.

Thanks.

**Comment by vidartf** [comment]
I'm not sure if git allows the show command to be extended. If you find any documentation that say this should be possible, I'm happy to help you find a solution for using that.

**Comment by tienduccao** [comment]
Hi @vidartf , currently I don't find any document.
So it means I can only use nbdime to view the diff between two commits and there's no way to view a commit in a similar fashion as nbdiff does?

**Comment by vidartf** [comment]
I'm sure you can write a small script to do what you want. The script would somehow need to read the content of any notebook files in the commit, and then it can send (pipe or as filepath) that content to either nbshow, or potentially jupytext.

**Comment by vidartf** [comment]
Best answer is likely here: https://stackoverflow.com/questions/17558221/how-can-i-view-the-output-of-git-show-in-a-diff-viewer-like-meld-kdiff3-etc
