### ISSUE TITLE
nbdiff-web: command not found

### ISSUE THREAD

**Issue by liao0038** [jupyter/nbdime#511]
1. pip install nbdime
2. nbdime config-git --enable --global
3. nbdiff-web master branch file-a file-b
get the following erors:
nbdiff-web: command not found

any advice? Thanks

**Comment by vidartf** [comment]
Seems weird. Both of the entry points are defined in the same place: https://github.com/jupyter/nbdime/blob/425c46df8f9814460c6445fa4fe5e2a711230e36/setup.py#L144-L147

It might be a problem with you install, so you might have some luck with uninstalling nbdime, and then reinstalling. If you are using anything other than pure pip (e.g. conda) the complexity of troubleshooting correctly quickly rises.

**Comment by vidartf** [comment]
Closing as stale. If anyone has more information, please comment, and we can reopen :)
