### ISSUE TITLE
Use config file When Comparing Notebooks in a UI

### ISSUE THREAD

**Issue by rrma** [jupyter/nbdime#513]
I am using nbdime in a jupyter lab environment. For a better comparison I usually ignore the output and the metadata of the notebooks (by using a config file where I set `"outputs": false`, `"metadata": false`). This works fine in the CLI.
For better user experience, It would be great if I can also ignore the outputs and metadata by default (=using the config) when using the jupyterlab-git integration ("git" button in the notebook).
As far as I have seen this is not possible at the moment, as this button uses the nbdime API which does not provide an option for using a configuration. 

Has anyone of you tried to use a configuration when comparing with the "git" button provided by juptyerlab-git (except the web-ui as this is not easy to use in a jupyter-lab environment)? Or does anyone know another way to compare the difference between two notebooks in a proper UI ignoring the output and metadata?

Add-On:
I have also tried to set options in the "Extension" section as in the documentation it says that this is then used when diffing with front-end extension (notebook or lab environment), e.g.
```
{
  "Extension": {
    "Ignore": {
      "/cells/*/outputs": true,
      "/cells/*/attachments": true,
      "/cells/*/metadata": true
    }
  }
}
```
Unfortunately, this did not work for me.

**Comment by vidartf** [comment]
When using the listed configuration, I see outputs ignored (listed as "outputs unchanged"). Note that for an updated config to take hold, the notebook/lab server needs to be restarted (config loaded on initialization).

**Comment by rrma** [comment]
I also tried to restart the jupyter lab server but it did not apply the changes. I also tried a different , very simple, configuration:
```
{
  "Extension": {
    outputs:false
  }
}
```
Unfortunately, it did not apply the configuration. Any advice?

**Comment by vidartf** [comment]
Which version of nbdime are you using? And are you seeing this for both notebook extension and lab, or only one of them?

**Comment by rrma** [comment]
I am using nbdime v2.0.0

**Comment by vidartf** [comment]
It is possible that this was the same as https://github.com/jupyter/nbdime/issues/529, in which case #542 ought to have fixed it. Can you confirm if version 2.1.0 fixes this?

**Comment by rrma** [comment]
Could not reproduce the issue after updating. Will resolve ticket.
