### ISSUE TITLE
404 on /nbdime/api/isgit?[number]

### ISSUE THREAD

**Issue by jeanmonet** [jupyter/nbdime#522]
Hi,

Running Jupyter Lab 2.1.0 with Python 3.8 on Ubuntu 18.04
Fresh install of nbdime (extension enabled) + build (as of today): `nbdime-jupyterlab v2.0.0`

I get 404 error on path to `/nbdime/api/isgit...`, can't tell what goes wrong.

More generally, is the path `/nbdime/...` supposed to hit a specific OS directory?

**Comment by vidartf** [comment]
You most likely need to enable the nbdime server extension. See the docs: https://nbdime.readthedocs.io/en/latest/extensions.html If `jupyter serverextension list` says the server extension is already disabled, then please include the server log output so we can look for any relevant log entries.

**Comment by jeanmonet** [comment]
Tested again: removed and re-installed the extension (which triggered a re-build of jupyter lab). I then manually enabled the extension:

```
>>> jupyter labextension enable nbdime-jupyterlab
>>> jupyter labextension list
JupyterLab v2.1.0
Known labextensions:
   app dir: /path/anaconda3/envs/python38/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @krassowski/jupyterlab-lsp v1.0.0 disabled OK
        jupyter-matplotlib v0.7.2  enabled  OK
        nbdime-jupyterlab v2.0.0  enabled  OK
```

When starting jupyer lab, I can see the following console output (and the git button is grayed in jupyter lab itself):

```
[D 21:19:42.930 LabApp] Fetching URL: https://registry.yarnpkg.com/nbdime-jupyterlab
...
[W 21:19:43.346 LabApp] 404 POST /nbdime/api/isgit?1587410383290 (127.0.0.1) 43.19ms referer=https://host/lab/workspaces/laloi
```

The javascript console in the browser also outputs 404 error when attempting to `POST /nbdime/api/isgit?1587410383290`.

Can't think of any other log entries that would be relevant?
