### ISSUE TITLE
default args seem to overwrite options set in config files

### ISSUE THREAD

**Issue by Pugio** [jupyter/nbdime#529]
I'm trying to ignore specific metadata fields when using `nbdiff` (v 2.0.0) with a config like:

```json
{
   "Diff":{
      "Ignore": {
           "/cells/*/outputs": true,
           "/cells/*/metadata": ["ExecuteTime"],
           "/cells/*/execution_count": true
      }
   }
}
```

This doesn't work, as the defaults specified in https://github.com/jupyter/nbdime/blob/88044071ed21323e8a04c31134a6315c95d41b5f/nbdime/diffing/notebooks.py#L579-L589 – called during argument parsing at: https://github.com/jupyter/nbdime/blob/88044071ed21323e8a04c31134a6315c95d41b5f/nbdime/args.py#L386-L390 – seem to overwrite the ones loaded from the config file.

This means I can't use any custom Ignores, and am stuck at the level of resolution of the five basic types of ignorables (sources, outputs, etc.).

I am trying to set this config file as a standard for my git project. Am I missing something? I feel as though I must be because I can't see how this was ever supposed to work. How can I get `nbdiff` to honor my `"Ignore:"` options?

Thank you!

**Comment by vidartf** [comment]
Thank you for the report! This does indeed seem to be quite a bad bug!

I think the behavior we would ideally want here is:
- Have the default diff ignores be populated from the config.
- If any flags are specified:
  - A specified flag will override that value in the config.
  - A non-specified flag will set the value to the opposite of the specified flags, iff there is no value already specified by the config.

As you correctly point out, the current code does not respect the config values, so we should:
- Write some tests that checks how the config system and ignore flag system behave when combined.
- Fix the code.

I think I see how this can be achieved without too much effort, so I'll ping you once I have a PR if you would like to test it.

**Comment by Pugio** [comment]
That would be great, thank you! Looking forward to the PR. (Apologies that I don't have time to try to write it myself at the moment.)

**Comment by vidartf** [comment]
I did a minimal fix PR here: https://github.com/jupyter/nbdime/pull/542

It does not implement the "ideal" logic outlined above, but does at least allow config values to be used if no flags are specified. I'll add some tests, but sharing for now to allow input/testing from you or others.

**Comment by vidartf** [comment]
Closing this for now. If anyone has some good use cases that doesn't work with the new setup, please comment, and I will reopen :)
