### ISSUE TITLE
Jupyter lab extension fails in Jupyter Lab 2.2.0 - downgrade to 2.1.0 requred

### ISSUE THREAD

**Issue by sethgilchrist** [jupyter/nbdime#531]
JupyterLab 2.2.0 emits the following error in the browser console when the UI button is clicked:

Uncaught (in promise) TypeError: Cannot read property 'baseUrl' of undefined

I found that downgrading to JupyterLab 2.1.0 fixes the issue.

**Comment by vidartf** [comment]
Thanks! This seems to be due to a breaking change in lab, see the cross-referenced issue above.

**Comment by vidartf** [comment]
Fixed by #538 by @deanp70 , and just released 👍
