### ISSUE TITLE
Git Integration: git diff not defaulting to nbdime diff

### ISSUE THREAD

**Issue by Per48edjes** [jupyter/nbdime#532]
I can't seem to quite achieve the intended behavior per the [docs](https://nbdime.readthedocs.io/en/stable/vcs.html) re: Git integration. I have installed `nbdime` into my virtual env, stepped into the virtual env, and registered the drivers via `git-nbdiffdriver config --enable`.

While the tool is great when called upon in the command line (e.g., `nbdime-web diff`, `nbdime diff`), whenever I'm working and run a `git diff`, I don't get the nice diff format generated by `nbdime`.

My `.gitattributes` looks like the following in my repo:

```git
# This is for a different package (nbstripout)
*.ipynb filter=nbstripout

*.ipynb diff=jupyternotebook
*.ipynb merge=jupyternotebook

```

And my `.git/config` file looks like this:

```git
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
         # Omitted :) 
[branch "master"]
	remote = origin
	merge = refs/heads/master
[filter "nbstripout"]
	# Omitted :)
	smudge = cat
[diff "jupyternotebook"]
	command = git-nbdiffdriver diff
[merge "jupyternotebook"]
	driver = git-nbmergedriver merge %O %A %B %L %P
	name = jupyter notebook merge driver
[difftool "nbdime"]
	cmd = git-nbdifftool diff \"$LOCAL\" \"$REMOTE\" \"$BASE\"
[difftool]
	prompt = false
[mergetool "nbdime"]
	cmd = git-nbmergetool merge \"$BASE\" \"$LOCAL\" \"$REMOTE\" \"$MERGED\"
[mergetool]
	prompt = false
```

Seems that everything is in place. What am I missing? 🤔  Anywho, very appreciative of this utility!

**Comment by vidartf** [comment]
Unfortunately, git doesn't always use the external diff drivers. I think a filter is one of the things that interfere with this. As this is outside the control of nbdime (nbdime never gets invoked) it is quite hard to do anything about it, other than to recommend to use nbdiff..

**Comment by Per48edjes** [comment]
I see -- thanks for taking the time to explain that!

**Comment by vidartf** [comment]
Ah. I just realized, you might simply need to add the `--use-filter` option for the `git-nbdiffdriver diff` command.
