### ISSUE TITLE
422 Unprocessable Entity when using nbdime mergetool

### ISSUE THREAD

**Issue by Weisheng97** [jupyter/nbdime#536]
<img width="868" alt="Capture" src="https://user-images.githubusercontent.com/52645050/90708072-8bce1a00-e2cb-11ea-818c-881deb09cfe0.PNG">
<img width="910" alt="Capture1" src="https://user-images.githubusercontent.com/52645050/90708098-9dafbd00-e2cb-11ea-8999-90720a25313e.PNG">

**Comment by vidartf** [comment]
So this is nbdime claiming that one of the three parts (base in this case) are not a valid Notebook (JSON format issue?). You can see that it prints the temporary path of the file on the second to last line. Are you able to inspect that file and/or share it ?

**Comment by vidartf** [comment]
Actually, from that trace, it looks like base is empty, and that this is a conflict between two branches both adding a file with the same path (does that seem right?). If you can confirm that this is the case, I can check the code in question.

**Comment by Weisheng97** [comment]
Yup, that should be the case. I currently testing if NBdime mergetool works by creating a repository with two branches (master and b1) and forcing a merge conflict. Files from two branches are from the same local folder (evaluation notebook).

**Comment by Weisheng97** [comment]
I managed to fix a similar issue by adding a notepad file named .gitignore, to ignore the checkpoint folder.
<img width="148" alt="Capture111" src="https://user-images.githubusercontent.com/52645050/90860101-01b1ae80-e3bc-11ea-9533-dabafbe562b8.PNG">

**Comment by Weisheng97** [comment]
Sorry for the late reply. I am using git version 2.24.1.windows.2 and using windows 10 pro. No other git extensions were involved.
