### ISSUE TITLE
Git button is disabled after following nbdime installation instructions

### ISSUE THREAD

**Issue by orome** [jupyter/nbdime#537]
Following installation of nbdime, the git button in Jupyter Lab notebooks is disabled. Hovering over the button now shows 

> Display nbdiff from git HEAD ...

but clicking the button has no effect. Diffs from within the git UI in the sidebar work correctly however.

jupyterlab 2.2.6

**Comment by vidartf** [comment]
This is probably caused by the bug here: https://github.com/jupyter/nbdime/issues/531 Closing as a duplicate. Please comment if you believe this issue to a separate problem.

**Comment by orome** [comment]
@vidartf  Maybe; we'll see.
