### ISSUE TITLE
nbdiff shows stale version of the file if there's a git filter modifies the notebook

### ISSUE THREAD

**Issue by imrehg** [jupyter/nbdime#548]
Seems like `nbdiff` set up with `git` is behaving strangely if there's another [`filter` attribute](https://git-scm.com/docs/gitattributes#_filter) set up that modifies the notebooks that it would show diffs for. 

I'm using [`nb-clean`](https://github.com/srstevenson/nb-clean) to automatically clean notebooks before committing them, using a git filter attribute. However, `git diff --cached` (using `nbdiff`) shows still the non-cleaned version (that's still in disk, but not what's in the staging area), even though checking with `git show` after the commit shows that the proper clean version was committed. 

Any idea why is the diff showing the non-filtered version of the file added to staging?

### How to reproduce:

1. set up an empty git repo
2. install `nbdime`, `nb-clean` and `jupyter`: `pip install nbdime nb-clean jupyter`
2. set up git integration for the two tools:
  * `nbdime config-git --enable`
  * `nb-clean configure-git`
3. add an empty commit, so it's easier to compare things later: ` git commit --allow-empty -m "initial"`
4. create a new notebook, with a cell, and run it to have some output, save it. I basically just put a cell there and printed out the list `[1, 2, 3, 4]`
5. stage the new file
6. check the diff with `git diff --cached`, it shows something like this below:

```
nbdiff /dev/null test.ipynb
--- /dev/null  2020-10-27 17:56:45.702808
+++ test.ipynb  2020-10-27 17:55:20.612505
## added /cells:
+  code cell:
+    execution_count: 1
+    source:
+      [1, 2, 3,4 ]
+    outputs:
+      output 0:
+        output_type: execute_result
+        execution_count: 1
+        data:
+          text/plain: [1, 2, 3, 4]
+  code cell:

## added /metadata:
+  kernelspec:
+    display_name: Python 3
+    language: python
+    name: python3
+  language_info:
+    codemirror_mode:
+      name: ipython
+      version: 3
+    file_extension: .py
+    mimetype: text/x-python
+    name: python
+    nbconvert_exporter: python
+    pygments_lexer: ipython3
+    version: 3.8.5

## added /nbformat:
+  4

## added /nbformat_minor:
+  4
```

7. if now I disable the git integration `nbdime config-git --disable`, the diff will show the cleaned file

```
diff --git a/test.ipynb b/test.ipynb
new file mode 100644
index 0000000..4c91f4d
--- /dev/null
+++ b/test3.ipynb
@@ -0,0 +1,41 @@
+{
+ "cells": [
+  {
+   "cell_type": "code",
+   "execution_count": null,
+   "metadata": {},
+   "outputs": [],
+   "source": [
+    "[1, 2, 3, 4]"
+   ]
+  },
+  {
+   "cell_type": "code",
[... snip...]
```
but re-enabling the integration shows the not-cleaned version again.

After committing, `git diff HEAD~1 HEAD` shows the cleaned version properly.

**Comment by vidartf** [comment]
Hi, before digging into this, would you mind sharing which versions you have of git and nbdime? There is a known issue with some older versions of git, where we do not support integration with git filters.

**Comment by vidartf** [comment]
Ah, wait. I think you might just need to add `--use-filter` to the nbdime commands in your git config. It is not enabled by default, as there is some ambiguity in whether it should be applied or not when receiving the files from git. I don't think that should be an issue for you when the only filter is nb-clean.

**Comment by imrehg** [comment]
Ah, tried this out, and works well in my configuration. Can't believe that I didn't notice that flag. Thanks a lot for your insights and help!
