### ISSUE TITLE
Not working with Jupiter Lab 3.x?

### ISSUE THREAD

**Issue by orome** [jupyter/nbdime#555]
With Jupyter Lab 3.0 I get `The extension "nbdime-jupyterlab" is outdated`. Does this extension not currently work with 3.0?

**Comment by bollwyvl** [comment]
Looks like lab 3 support is a work in progress:

https://github.com/jupyter/nbdime/pull/551

Oh and lab 3 came out about 36hrs ago...

**Comment by stonebig** [comment]
hi, trying today with latest nbdime-3.0.0b1, I get this:
![image](https://user-images.githubusercontent.com/4312421/106354708-0c218e00-62f4-11eb-8999-dd714efb5b6a.png)

... is it the expectation or do I miss something ?

**Comment by RafalSkolasinski** [comment]
> hi, trying today with latest nbdime-3.0.0b1, I get this:
> ![image](https://user-images.githubusercontent.com/4312421/106354708-0c218e00-62f4-11eb-8999-dd714efb5b6a.png)
> 
> ... is it the expectation or do I miss something ?
> 
> (otherwise nbdiff-web works, and is nice)

That looks like would expect to see.
I am not getting this nice pop on `3.0.7` is the fix coming in `3.1`?

**Comment by vidartf** [comment]
The 3.0.0 release went out today. If there are any issues with the dist, please open a new issue!
