### ISSUE TITLE
Nbdiff not working as expected

### ISSUE THREAD

**Issue by tandelDipak** [jupyter/nbdime#556]
I have installed nbdime and then enabled it but it's not working. nbdiff is showing a lot of trash.

![Screenshot from 2021-01-06 22-02-26](https://user-images.githubusercontent.com/15157792/103794793-2eb0e600-506b-11eb-863a-c38459055446.png)

**Comment by vidartf** [comment]
Hopefully the command flags are helpful to you: https://nbdime.readthedocs.io/en/latest/cli.html#common-diff-options You can also make a use config to change the defaults: https://nbdime.readthedocs.io/en/latest/config.html

**Comment by tandelDipak** [comment]
@vidartf thanks for sharing the info. I tried with various combinations of flags but not able to get the output as shown in the docs. Can you help me with the configuration?

**"-OMA" flag doesn't remove execution count and few other things.**
![Screenshot from 2021-01-06 22-23-40](https://user-images.githubusercontent.com/15157792/103797326-58b7d780-506e-11eb-8ac2-d295ff7842eb.png)

**"-s" flag includes code cell and source line.** 
![Screenshot from 2021-01-06 22-23-50](https://user-images.githubusercontent.com/15157792/103797322-5786aa80-506e-11eb-92a5-c99e6f9ff895.png)

How to remove it?

**Comment by vidartf** [comment]
Ah, you have uncovered an omission in the docs. Thanks :) (fix in https://github.com/jupyter/nbdime/pull/557). The flag you want is probably `-D` / `--ignore-details`, which will ignore minor, emphemeral things like execution count.
