### ISSUE TITLE
"There are remaining conflicts" - where? I can't see them

### ISSUE THREAD

**Issue by mdavis-xyz** [jupyter/nbdime#563]
I'm trying to merge a notebook with the web tool.

I ticked "clear all outputs".
I've scrolled from top to bottom, and can't see any conflicts.

The word "conflict" does not appear when I use ctrl-f to search the whole page. Same with "resolve" (as in: "mark resolved")

But if I click "close tool", it says:

> There are remaining conflicts. Do you want to close anyway?

How am I supposed to tell what the conflicts are? What do conflicts look like?

Is there any documentation about how to read and use the web tool?
[this](https://nbdime.readthedocs.io/en/latest/vcs.html#merge-web-tool) is all I could find, and it only explains how to open the web tool.

Nothing appears in the browser console when I click "close tool"

**Comment by mdavis-xyz** [comment]
Is it supposed to look like this, with a red triangle? Because there are no red triangles on the page

![image](https://user-images.githubusercontent.com/7035647/104666910-173bc200-5729-11eb-80de-ff1860089bff.png)

**Comment by mdavis-xyz** [comment]
If I save anyway, the resulting file has no `>>>>` string, and jupyter opens it without complaining. So was this warning about there still being conflicts not correct?

**Comment by vidartf** [comment]
It is hard to say exactly what has gone wrong in this instance. If you have the opportunity to share a reproduction (e.g. share the notebooks that gave the problematic case), that would help in troubleshooting this. The best fallback in cases such as yours, is to use the mergedriver, and directly open the conflicted notebook in your normal notebook editor.

**Comment by mdavis-xyz** [comment]
I'm afraid I can't share this notebook, since it's got some sensitive code and outputs in it.

What is a user supposed to see when there's a merge clash? Is the image above what I'm supposed to see?

What about when I open the notebook in my normal notebook editor? (I assume you mean Jupyter Lab). I didn't see anything there. Am I supposed to click the "git" button in that? Or do you expect Jupyter Lab to pop up a warning about a clash?

What about when I open the notebook up in a text editor? Should I see `>>>` and `<<<` ?

**Comment by vidartf** [comment]
If you have installed the [nbdime mergedriver](https://nbdime.readthedocs.io/en/latest/vcs.html#merge-driver), ">>>>>" indicators will be inserted into the notebook, but in a way where it is still a valid notebook document, and where those indicators will be visible with a regular notebook editor (for comparison, regular git will simply insert the indicators directly in the document, which will be invalid JSON).

Normally the webtool should be pretty visible about where the conflict is, but it might be something unexpected. If you are able to extract the base, local and remote version of the document, you can run `nbmerge --decisions base.ipynb local,ipynb remote.ipynb` to have a text version of the conflicts printed to the conflict. That output should be possible to make "anonymous" for sharing by some manual deletions, but still be very informative for troubleshooting.

**Comment by mdavis-xyz** [comment]
I finished merging that particular example (assuming that it was fine since I couldn't see `>>>` in the text file).

I haven't had any other git clashes since then to test on.
