### ISSUE TITLE
MathJax.js is not available in diffs since migration to jupyter_server

### ISSUE THREAD

**Issue by krassowski** [jupyter/nbdime#573]
Comparing [jupyter_server/search?q=mathjax_url](https://github.com/jupyter-server/jupyter_server/search?q=mathjax_url) and [notebook/search?q=mathjax_url](https://github.com/jupyter/notebook/search?q=mathjax_url) it looks that:
- the [handler](https://github.com/jupyter-server/jupyter_server/blob/3135bd6f764210cf1d084cfec3cb8ad218a4340a/jupyter_server/base/handlers.py#L217-L222
) was kept in the `jupyter_server`, but
- the actual mathjax javascript was removed from `jupyter_server` and is only present in `notebook`: [notebook/static/base/js/mathjaxutils.js](https://github.com/jupyter/notebook/blob/2ba296039aa70afbfd90630fea14bb8461b40410/notebook/static/base/js/mathjaxutils.js)
- the mathjax config was also removed from `jupyter_server` and is only present in `notebook`: [notebook/notebookapp.py#L1344-L1365](https://github.com/jupyter/notebook/blob/dc8b70519f61540cf3869ccadbff3c47d355c7b2/notebook/notebookapp.py#L1344-L1365)

_Originally posted by @krassowski in https://github.com/jupyter/nbdime/issues/566#issuecomment-802894817_

**Comment by krassowski** [comment]
One solution would be to default to the CDN, as is currently the case in `jupyterlab_server`:

https://github.com/afshin/jupyterlab_server/blob/0e5830a6e05492d1e82c1ae4ee7d12c8a5e074e9/jupyterlab_server/handlers.py#L92-L100

**Comment by vidartf** [comment]
I started work on https://github.com/jupyter-server/jupyter_server_mathjax to solve this.
