### ISSUE TITLE
nbdime enable --sys-prefix doesn't work

### ISSUE THREAD

**Issue by jabbera** [jupyter/nbdime#575]
using 3.0.0b1 and JL 3.0.11 you can't enable the extension with:
```
nbdime enable --sys-prefix
```

The command fails because labextension enable doesn't take the argument --sys-prefix:

https://github.com/jupyter/nbdime/blob/f6beb6001537bba841625b5cc7011dd5d4fec536/nbdime/__main__.py#L55

**Comment by vidartf** [comment]
Thanks. Closing as a duplicate of https://github.com/jupyter/nbdime/issues/479 .
