### ISSUE TITLE
How to do nbdiff-web between 2 branches on uncommited code

### ISSUE THREAD

**Issue by BartlomiejSkwira** [jupyter/nbdime#588]
Let's say I'm on a new branch and I have a file called `file1.ipynb` which has local modifications. I'm trying to do a diff between 2 branches on this modified, uncommitted file. 
This doesn't work:
```
nbdiff-web develop HEAD file1.ipynb
```
I get something like:
```
/Users/user/.pyenv/versions/3.8.9/lib/python3.8/site-packages/jupyter_server/transutils.py:13: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
  warnings.warn(warn_msg, FutureWarning)
```
When I commit the `file1.ipynb` file and do the same thing it works. 

I know that git works on commits, but still, I wanted to ask if there is a way to do a diff without commits?

**Comment by vidartf** [comment]
What would the git command be for diffing your file? I would expect `git diff develop -- file1.ipynb`. For nbdime I expect `nbdiff-web develop file1.ipynb` should work for diffing against the working tree ?

**Comment by BartlomiejSkwira** [comment]
I guess if this works for committed code
`nbdiff-web develop HEAD file1.ipynb` 
Then an additional flag would probably be ok
`nbdiff-web --uncommitted develop HEAD file1.ipynb` 
Or something similar. 

Ps: I don't want to enforce any standard on how this should work - I would be happy with any implementation . Right nowa s a workaround I just do a WIP commit, check the nbdiff and reset --soft the commit.

**Comment by vidartf** [comment]
I'm confused. What happens when you run `nbdiff-web develop file1.ipynb` as I suggested ?

**Comment by BartlomiejSkwira** [comment]
@vidartf That's it! Thanks, this is what I was looking for!
