### ISSUE TITLE
difftool should show render outputs

### ISSUE THREAD

**Issue by minrk** [jupyter/nbdime#59]
The same OutputArea machinery should be used to render outputs, so they look the same as in the notebook.

**Comment by vidartf** [comment]
Currently, the web difftool uses `OutputWidget` to render outputs, so each individual output should render the same. If the complete OutputArea machinery was used, you would have to render two `OutputAreaWidget`s side-by-side. To differentiate between changed and unchanged outputs within one cell's outputs, you would then have to modify the rendered outputs afterwards (which might or might not be trivial). The individual rendering is also used such that text type outputs can be show/highlighted using CodeMirror editors.

Do you have any specific examples of things that render differently?

**Comment by vidartf** [comment]
Is this OK now?

**Comment by minrk** [comment]
yup, this is okay
