### ISSUE TITLE
3.1.0 release

### ISSUE THREAD

**Issue by mlucool** [jupyter/nbdime#598]
Hi @vidartf,

I don't see 3.1.0 in https://github.com/jupyter/nbdime/releases nor the [changelog](https://github.com/jupyter/nbdime/blob/master/docs/source/changelog.md). I do see it on pypi. Can these be updated?

Thanks!

**Comment by vidartf** [comment]
forgot to push the tags, thanks for pointing it out!

**Comment by vidartf** [comment]
(I also pushed an update to the changelog)

**Comment by Apteryks** [comment]
Hi, I may be confused, but I don't see a recent tag for 3.1.0 (or 3.1.1).  Which tag corresponds to the latest pypi release?

**Comment by vidartf** [comment]
@Apteryks That's weird, it should be here: https://github.com/jupyter/nbdime/releases/tag/3.1.1

**Comment by Apteryks** [comment]
I seem them now, not sure what happened :-)
