### ISSUE TITLE
git merge -X theirs produces unexpected conflict

### ISSUE THREAD

**Issue by joelsewhere** [jupyter/nbdime#606]
### Context

I am trying to split a jupyter notebook across different git branches, where one branch is the "edit branch" and the other branches contain different versions of the edit branch notebook. For this to work properly, I need to be able to run a `git merge -X theirs` where `theirs=<edit branch>`  to ensure all branches remain synchronized.

### The issue
Right now, whenever an edit is made to an edit branch, and the merge is run via `git-nbmergedriver`, the merge results in a conflict. When the same merge is run _without_ the mergedriver, there is no conflict. 

It looks like some meaningful work has been done to incorporate `ours`/`their` merge strategies in #38, so I'm not sure if I'm missing something obvious.

**Is it correct that the merge strategies from #38 are not activated with `git merge -X theirs`?**
    - If not, is there an alternative way to activate this type of merge via git? 

If this is not implemented I'd be happy to try and put together a proposal, but I might need some guidance about where to start.

**Comment by vidartf** [comment]
Unfortunately, git does not pass its strategy options on to the merge driver (see docs https://git-scm.com/docs/gitattributes#_defining_a_custom_merge_driver or source https://github.com/git/git/blob/142430338477d9d1bb25be66267225fb58498d92/ll-merge.c#L176-L238). There also isn't a good way in git to specify the driver to use via the cmd line, so it seems tough to workaround this by declaring multiple drivers as well :-/

The options I see are not straight forward, but maybe you can use them as a starting point to find something smarter:
- Declare multiple merge drivers in your git-config, and figure out an intelligent way to switch which driver to use.
- If you will *always* use a specific strategy for this repo, you can hard code the strategy into your driver command.
- You can do it as a two-step process: 1. have current flow where merge causes a conflict 2. resolve the conflict by calling `nbmerge <strategy flags here> <path to base file> <path to local file> <path to remote file>` and then using `git add` to mark as resolved.
- You can do a PR to nbdime adding support for setting the merge strategies options [via env vars](https://stackoverflow.com/questions/10551117/setting-options-from-environment-variables-when-using-argparse), and then you can have a little script that sets to vars temporarily before calling git merge.

The last option is probably the best one in the long term, but will of course not be available immediately 😄

**Comment by vidartf** [comment]
Closing as answered.
