### ISSUE TITLE
Is `--ignore-metadata` working?

### ISSUE THREAD

**Issue by michaelaye** [jupyter/nbdime#609]
I set up to use `--ignore-metadata` in git config:

```
diff.jupyternotebook.command=git-nbdiffdriver diff --ignore-metadata
```
but I still get an updated javascript part given in my diff?

```
diff --git a/01_dems.ipynb b/01_dems.ipynb
index e405343..bb10175 100644
--- a/01_dems.ipynb
+++ b/01_dems.ipynb
@@ -32,6 +32,1980 @@
    "execution_count": null,
    "metadata": {},
    "outputs": [
+    {
+     "data": {
+      "application/javascript": [
+       "\n",
+       "(function(root) {\n",
+       "  function now() {\n",
+       "    return new Date();\n",
+       "  }\n",
+       "\n",
+       "  var force = true;\n",
+       "\n",
.
.
.
```
Am I understanding something wrong in assuming that I shouldn't get this anymore with `ignore-metadata` ?

Versions: 
* nbdime 3.0.0b1 on linux
* python 3.8

**Comment by vidartf** [comment]
This isn't metadata, this is an output from executing the cell. The appropriate flag would be `--ignore-outputs`.

**Comment by vidartf** [comment]
Also, AFAICT from your output, nbdime is not being used here, but the normal git text differ.

**Comment by michaelaye** [comment]
thanks. i don't know why the normal git text differ is being used, considering that I have above shown setting, but that isn't your problem. ;)
