### ISSUE TITLE
Request: Provide nbdime as an extension for vscode (dependant upon vscode-jupyter)

### ISSUE THREAD

**Issue by DennisL68** [jupyter/nbdime#624]
If nbdime could be distributed as a vscode extension, that would simplify the life for a lot of data scientists and coders that are using Jupyter notebooks with vscode.

I've propsed this idea to the jupyter-vscode project in  
[Add nbdime as part of vscode-jupyter for proper diffing in Git #10742](https://github.com/microsoft/vscode-jupyter/discussions/10742)

**Comment by vidartf** [comment]
Vscode seems to have run with its own thing, so closing this.
