### ISSUE TITLE
Works in Jupyter Notebook, but doesn't show up in Jupyter Lab

### ISSUE THREAD

**Issue by JBlaschke** [jupyter/nbdime#625]
Following the instructions here: https://nbdime.readthedocs.io/en/latest/extensions.html I can get it to work in Jupyter Notebooks. But when look for the nbdime button in the toolbar of a notebook hosted by Jupyter Lab, I can't find it.

Note: I have Jupyter installed in a virtualenv, so I followed the instructions here: https://nbdime.readthedocs.io/en/latest/extensions.html using `--sys-prefix`:
```
jupyter serverextension enable --py nbdime --sys-prefix

jupyter nbextension install --py nbdime --sys-prefix
jupyter nbextension enable --py nbdime --sys-prefix

jupyter labextension install nbdime-jupyterlab
```

**Comment by fcollonval** [comment]
@JBlaschke for JupyterLab, installing the latest version with `pip` or `conda` should work out of the box (no other actions required).

Then you should see a _git_ button in the notebook toolbar like:

![](https://user-images.githubusercontent.com/10121753/191238274-e8f47e2c-866d-4fd7-a7b7-4b458dda9474.png)

**Comment by vidartf** [comment]
I assume Frederic's fix solved this issue, since no more details were shared. If not, please comment, and I will reopen.
