### ISSUE TITLE
Releases on github not showing 3.2.0 and seem off

### ISSUE THREAD

**Issue by fperez** [jupyter/nbdime#663]
Quick ping - @vidartf, something is off with the [releases page](https://github.com/jupyter/nbdime/releases) on github, it's showing 3.1.1 as if it had been made 2 days ago, which corresponds to your new 3.2.0 release. PyPI seems fine, the problem seems to be only on the github page.

Thx for the new release, btw!!

**Comment by vidartf** [comment]
Cheers. I wasn't really using the releases function of GH previously, but had to add one to get easy access to the "X commits to master since...". I've added 3.2.0 for now.

**Comment by fperez** [comment]
Awesome, many thanks!
