### ISSUE TITLE
Regression in 3.2.0 - nbddiff-wev exits after diffing the first notebook

### ISSUE THREAD

**Issue by xl0** [jupyter/nbdime#665]
I've just upgraded from 3.1.1 to 3.2.0 and I really appreciate that it now works with jupyter-server=2, but at least one thing is broken.

If I run `nbdiff-web` in my work directory with multiple notebooks having changes, only the first one will be shown in the newly opened tab, an nbdiff-web will exit as soon as the tab is closed.

```
$ nbdiff-web 
[I nbdimeserver:433] Listening on 127.0.0.1, port 34173
[I webutil:29] URL: http://127.0.0.1:34173/difftool
[I nbdimeserver:319] Closing server on remote request (1)
$
```

In 3.1.1, nbdiff-web would go through all the notebooks, opening new tabs one by one as I close the previous one. Maybe not the ideal experience, but it worked

```
$ nbdiff-web 
[I nbdimeserver:422] Listening on 127.0.0.1, port 40707
[I webutil:29] URL: http://127.0.0.1:40707/difftool
[I nbdimeserver:315] Closing server on remote request
[I nbdimeserver:422] Listening on 127.0.0.1, port 43729
[I webutil:29] URL: http://127.0.0.1:43729/difftool
[I nbdimeserver:315] Closing server on remote request
[I nbdimeserver:422] Listening on 127.0.0.1, port 43347
[I webutil:29] URL: http://127.0.0.1:43347/difftool
[I nbdimeserver:315] Closing server on remote request
[I nbdimeserver:422] Listening on 127.0.0.1, port 40951
[I webutil:29] URL: http://127.0.0.1:40951/difftool
...
...
...
```

Is this a bug, or am I using the tool incorrectly?

**Comment by vidartf** [comment]
Can reproduce. I think this is a longer standing bug that a recent fix of a different problem has now revealed. I'll have a look to see if I can fix it,
