### ISSUE TITLE
CM6: Fix background color

### ISSUE THREAD

**Issue by vidartf** [jupyter/nbdime#675]
In lab 4, the theme for a code editor is only scoped on the notebook and console classes (in a bit of a bleedthrough in the lab codebase: the specific extensions "notebook" and "console" are special cased in the generic "codemirror" package): 

https://github.com/jupyterlab/jupyterlab/blob/1d989bad87e89307a336d2f671c9cc98ec37f5e9/packages/codemirror/src/theme.ts#L27C1-L29

We should either see if we can add to the global theme such that our diff/merge views also get this styling, or create a specific selector outside of the theme system.

**Comment by HaudinFlorence** [comment]
> We should either see if we can add to the global theme such that our diff/merge views also get this styling, or create a specific selector outside of the theme system.

@vidartf I can try to work on it. Is there a special reason to have a grey background and not something closer to notebook cells ? What is best to choose between the 2 options mentioned above.

**Comment by vidartf** [comment]
> grey background and not something closer to notebook cells ? 

To clarify: Notebook cells *do* have a gray background. Any usage of codemirror outside of notebook and console on the other hand now (with lab 4) has a default background of white. We should try to mimic the look in notebooks as much as possible, so we should also use the same theming.

**Comment by vidartf** [comment]
> What is best to choose between the 2 options mentioned above.

The first option is probably more robust / future-proof, but the second option will be simpler to implement (the way CM styling works now).

**Comment by HaudinFlorence** [comment]
@vidartf Thanks for your input and for the precisions. I opened a PR to try to fix the issue https://github.com/jupyter/nbdime/pull/714.

**Comment by HaudinFlorence** [comment]
I think that this issue can be closed.

**Comment by vidartf** [comment]
Thanks
