### ISSUE TITLE
CM6: Restore collapser

### ISSUE THREAD

**Issue by fcollonval** [jupyter/nbdime#679]
This is a follow-up of https://github.com/jupyter/nbdime/pull/673 in which the collapser of unchanged code was removed (as not ported from CM5 to CM6).

Some solution could probably be extrapolated from https://github.com/codemirror/merge

**Comment by krassowski** [comment]
https://github.com/codemirror/merge appears to be using `Decoration.replace` which was also recommended recently in a [related topic](https://discuss.codemirror.net/t/gutter-plugin-for-github-like-code-hiding/7067). Is there a reason for not depending on https://github.com/codemirror/merge directly? The decoration widgets are modular so possibly we could just import them (possibly with tiny upstream adjustments).

**Comment by JohanMabille** [comment]
>  Is there a reason for not depending on https://github.com/codemirror/merge directly?

As @fcollonval said, nbdime defines its own data structure for diff chunks, not compatible with the one in codemirror/merge. Besides, codemirror/merge provides a 2 ways view only, while nbdime also provides 3 and 4 ways views, which require extra padding for alignment, so I don't see how we could reuse the classes defined in codemirror/merge.

Regarding the decorations defined in codemirror/merge, they seem to be private to me (but I might be wrong here, I'm definitely not a TypeScript expert ;)).

Therefore I don't really see how we could benefit from depending on codemirror/merge (but again I might have missed things)

**Comment by krassowski** [comment]
> Regarding the decorations defined in codemirror/merge, they seem to be private to me

You are right, this is (among others) what I meant by "tiny upstream adjustments" ;)

Thank you for explaining the rationale in more detail. I would still consider it worthwhile trying to contribute some of the things upstream and then reusing theme here, but of course this has an overhead and we may prefer to have a custom implementation for time being.
