### ISSUE TITLE
Identical content editor are collapsed

### ISSUE THREAD

**Issue by fcollonval** [jupyter/nbdime#718]
From jupyterlab-git example, single cell added or unchanged have their content collapse as identical. We should not collapse the content in such case.

![image](https://github.com/jupyter/nbdime/assets/8435071/2d9f17dc-e034-411a-b07f-c5938da4074c)

There is also the case of the notebook metadata. But the issue is larger as the collapse widget title is wrong by announcing there is a change even when there is none. And in addition, it displays 4 editors even if there are no changes.

**Comment by fcollonval** [comment]
#719 solved the first part - the part about the notebook metadata still needs fixing.

**Comment by vidartf** [comment]
BTW: When doing a comparison between stable / RC, I notice the stable also lists metadata as having changes, even when there are none, so this might not be a regression (the metadata bit)? Rather, the full collapse just highlights the issue more clearly?

**Comment by fcollonval** [comment]
> this might not be a regression (the metadata bit)?

Yes this is not a regression. But it will definitely be interesting for the user to know if the metadata have changed or not.

> Rather, the full collapse just highlights the issue more clearly?

Yes indeed.
