### ISSUE TITLE
CM6 tail: Cell spacing

### ISSUE THREAD

**Issue by vidartf** [jupyter/nbdime#720]
Here are screenshots of how a merge looks before and after the CM6 / lab 4 rewrite:

![image](https://github.com/jupyter/nbdime/assets/510760/181a3b11-4594-4aca-a333-b8bb3b23aed7) ![image](https://github.com/jupyter/nbdime/assets/510760/d9dae2d1-b220-455e-a940-8b96a44bb8c7)

(old version on left, master on right)

The main thing to note is how the vertical spacings have been messed up. These should either be brought in line with the old style, or at least reviewed to be coherent (all things from a single cell should be spaced together).

**Comment by krassowski** [comment]
Closing as fixed by https://github.com/jupyter/nbdime/pull/728, please reopen if needed.
