### ISSUE TITLE
CM6 tail: Merge view cell drag and drop

### ISSUE THREAD

**Issue by vidartf** [jupyter/nbdime#721]
After the CM6 rewrite, the drag-and-drop of cells in the merge view is no longer working:

![image](https://github.com/jupyter/nbdime/assets/510760/a24d436e-a79d-4594-a2cf-a27092dbad35)

The highlighted handles are meant to allow users to re-order cells in the merge. Outputs were also re-orderable, but I haven't checked the behavior on master for this.

**Comment by HaudinFlorence** [comment]
@vidartf Could you please elaborate more about the expected behavior of the drag-drop functionality ? I tried it in the cm5 version but I don't understand how it should work. Thanks.

**Comment by HaudinFlorence** [comment]
@vidartf You are right, it does not work anymore in the CM6. To be fair, I was not aware of this functionality and I am not sure how much work it is to restore it.
