### ISSUE TITLE
Generate notebook representation of merge result with conflicts included

### ISSUE THREAD

**Issue by martinal** [jupyter/nbdime#9]
Just as text merge tools can generate a text file containing the merge result and conflicts inlined in the text file with markers <<< >>> for manual editing in a text editor, we can generate a notebook file with similar markers inside code cells and let the user resolve conflicts in cell sources using standard jupyter notebook editing tools. Editing output cells is not considered interesting.

**Comment by martinal** [comment]
This is a subset of:

https://github.com/martinal/nbdime/issues/19

**Comment by ellisonbg** [comment]
@cameronoelsen
